module ReviewConfig exposing (config)

{-| The elm-review configuration for the `M3e` generated component library and
the `docs/` application.

The library lives in `src/*` (generated by `elm-cem`); the docs app
lives in `docs/app/`. This config is run from `docs/` against `docs/elm.json`
(whose source-dirs cover `app`, `docs/src`, `.elm-pages`, `../src`,
`../docs/kit`) via:

    cd docs && node_modules /. bin / elm - review --config ../review --compiler node_modules/.bin/elm

See `review/README.md` for the rationale behind each rule and every relaxation.

-}

import Cem
import CodegenReviewConfig
import CognitiveComplexity
import Docs.ReviewAtDocs
import Docs.ReviewLinksAndSections
import Docs.UpToDateReadmeLinks
import M3e.Review.Facts
import NoConfusingPrefixOperator
import NoDebug.Log
import NoDebug.TodoOrToString
import NoExposingEverything
import NoFunctionOutsideOfModules
import NoImportingEverything
import NoMissingTypeAnnotation
import NoMissingTypeAnnotationInLetIn
import NoMissingTypeExpose
import NoModuleOnExposedNames
import NoPrematureLetComputation
import NoProprietaryDsClasses
import NoRedundantlyQualifiedType
import NoSimpleLetBody
import NoUnnecessaryTrailingUnderscore
import NoUnused.CustomTypeConstructorArgs
import NoUnused.CustomTypeConstructors
import NoUnused.Exports
import NoUnused.Modules
import NoUnused.Parameters
import NoUnused.Patterns
import NoUnused.Variables
import Review.Rule as Rule exposing (Rule)
import Simplify


config : List Rule
config =
    List.concat
        [ unused
        , common
        , docs
        , correctness
        , materialDiscipline
        , codegenAware
        , CodegenReviewConfig.config
        , codeStyle
        , complexity
        , toHtmlGate
        ]
        |> List.map (ignoreElmPages >> ignoreLibraryTests)


{-| `.elm-pages/` is fully generated routing/metadata — NO rule should lint it
(unlike `vendor/`, where correctness rules intentionally still run). Applied to
EVERY rule here so generated routing code never enters the suppression baseline.
-}
ignoreElmPages : Rule -> Rule
ignoreElmPages =
    Rule.ignoreErrorsForDirectories [ ".elm-pages/" ]


{-| The `tests/` project holds the library's own tests: `tests/tests/`
(`IrCoreTest`/`NodeSlotTest` — elm-test unit tests that legitimately import the
opaque-IR interiors and use `Seam` to construct fixtures) and
`tests/build-shape/` (compile-only type-behavior fixtures whose bindings are
deliberately unused/un-annotated to exercise inference). None of it is docs-app
source, so it is not gated by the docs review — ignore the whole `tests/` tree
for EVERY rule. Two path forms cover root- vs docs/-relative runs.
-}
ignoreLibraryTests : Rule -> Rule
ignoreLibraryTests =
    Rule.ignoreErrorsForDirectories [ "tests/", "../tests/" ]


{-| `src/` is entirely generated by `elm-cem` (the typed component
library plus its verbatim runtime templates). Style and documentation rules
should not gate on generated code; correctness rules (`Simplify`, `NoDebug.*`,
and the Material-discipline rules) still run on it.

Two path forms: `"src/"` (from repo root) and
`"../src/"` (from docs/, whose elm.json lists `../src`
as a source directory). Both are present so the ignore works regardless of the
working directory the review runs from.

-}
ignoreVendor : Rule -> Rule
ignoreVendor rule =
    rule
        |> Rule.ignoreErrorsForDirectories [ "src/M3e/", "../src/M3e/" ]
        |> Rule.ignoreErrorsForFiles [ "src/M3e.elm", "../src/M3e.elm" ]


{-| `.elm-pages/` contains auto-generated routing and metadata. Treat it the
same as the generated `src/` library — correctness rules still run,
style rules do not.
-}
ignoreGenerated : Rule -> Rule
ignoreGenerated rule =
    rule
        |> Rule.ignoreErrorsForDirectories [ "src/M3e/", "../src/M3e/", ".elm-pages/" ]
        |> Rule.ignoreErrorsForFiles [ "src/M3e.elm", "../src/M3e.elm" ]



-- UNUSED ---------------------------------------------------------------------


unused : List Rule
unused =
    [ NoUnused.Variables.rule |> ignoreGenerated
    , NoUnused.CustomTypeConstructors.rule [] |> ignoreGenerated |> ignorePublicApi |> ignoreElmPagesUserModules
    , NoUnused.CustomTypeConstructorArgs.rule |> ignoreGenerated
    , NoUnused.Exports.rule |> ignoreGenerated |> ignorePublicApi |> ignoreLayoutVocabulary |> ignoreKitVocabulary |> ignoreElmPagesUserModules
    , NoUnused.Modules.rule |> ignoreGenerated |> ignorePublicApi
    , NoUnused.Parameters.rule |> ignoreGenerated
    , NoUnused.Patterns.rule |> ignoreGenerated
    ]


{-| `docs/src/Layout.elm` is the docs app's layout-vocabulary module: a
deliberately-complete, symmetric set of presets + escapes (`row`/`rowWith`/…)
that exists as an intentional API surface, exactly like a design-system module.
Not every primitive is used by the current pages, and that is fine — they are
provided on purpose. Exempt it from `NoUnused.Exports` (config-level intent, not
a suppression-baseline debt). Two path forms cover root- vs `docs/`-relative runs.
-}
ignoreLayoutVocabulary : Rule -> Rule
ignoreLayoutVocabulary =
    Rule.ignoreErrorsForFiles [ "src/Layout.elm", "docs/src/Layout.elm" ]


{-| `docs/kit/` is the docs app's userland design-system kit — the
sanctioned home for the visual seam (`Kit`, `Kit.Surface`, `Kit.Shape`). Like
`Layout.elm`, it deliberately exposes a complete, symmetric vocabulary (every M3
type-scale role, color role, and corner token), so not every export is used by
the current pages — that is intentional API surface, not dead code. Two path
forms cover root- vs `docs/`-relative runs.
-}
ignoreKitVocabulary : Rule -> Rule
ignoreKitVocabulary =
    Rule.ignoreErrorsForDirectories [ "kit/", "docs/kit/" ]


{-| `app/Effect.elm` and `app/View.elm` are the elm-pages "user-owned" framework
modules. The framework wires them through generated code in `.elm-pages/` (which
every rule already ignores), so `elm-review` — which only sees the app source —
reads their framework-contract surface as unused:

  - `Effect`'s `Submit`/`SubmitFetcher`/`SetField`/`FetchRouteData` constructors and
    the `Effect(..)` export back `perform`'s helper record, which generated `Main`
    builds and calls; they are the standard elm-pages form/fetcher effect scaffold,
    live-by-contract even when no current page submits a form.
  - `testPerform` is the required companion to `perform` for the `Test.PagesProgram`
    harness.
  - `View`'s `freeze`/`freezableToHtml`/`htmlToFreezable` are the frozen-view
    build-time-render + client-adoption seam, transformed by a codemod (see the
    module docs) — deliberate infra, not dead code.

Exempt both files from the unused-export/constructor rules (config-level intent,
not a suppression-baseline debt). Two path forms cover root- vs docs/-relative runs.

-}
ignoreElmPagesUserModules : Rule -> Rule
ignoreElmPagesUserModules =
    Rule.ignoreErrorsForFiles
        [ "app/Effect.elm", "docs/app/Effect.elm", "app/View.elm", "docs/app/View.elm" ]


{-| `NoMissingTypeExpose` is a package-API rule: "an exposed function's signature
mentions a private type, so a consumer could not name it." elm-pages `Route`
modules are application code — nothing imports them except generated glue, and the
exposed `route` value's signature necessarily mentions the module-private
`RouteParams` (plus page-local data types like `Component`/`UsageExample`).
Exposing those would be meaningless ceremony, so relax the rule for `app/Route/`.
Two path forms cover root- vs docs/-relative runs.
-}
ignoreRouteModules : Rule -> Rule
ignoreRouteModules =
    Rule.ignoreErrorsForDirectories [ "app/Route/", "docs/app/Route/" ]


{-| A published library's whole point is exports/modules/constructors that are
unused _by itself_ — every `M3e.*` value and every exposed `Variant(..)`-style
constructor exists for consumers we cannot see in this repo.

Reviewing the library in isolation (no docs app, no consuming app) makes
`NoUnused.Exports`, `NoUnused.Modules`, and `NoUnused.CustomTypeConstructors`
fire on the entire public API. We ignore the generated `src/M3e/`
directory (and the top-level `src/M3e.elm` barrel, whose re-exports
are unused-by-self until consumers import them) for those rules so they still
catch genuinely-dead code in any non-public helper directories while leaving the
public surface alone.

`NoMissingTypeExpose` is relaxed here for the same directory: the generated
phantom-typed API deliberately keeps some infra types private, which the rule
reads as a "private type used by an exposed type".

Two path forms are listed: `"src/M3e/"` (when review runs from the
repo root) and `"../src/M3e/"` (when it runs from `docs/`, whose
elm.json lists `../src` as a source directory). Both must be present
so that the ignore works regardless of working directory.

-}
ignorePublicApi : Rule -> Rule
ignorePublicApi rule =
    rule
        |> Rule.ignoreErrorsForDirectories [ "src/M3e/", "../src/M3e/" ]
        |> Rule.ignoreErrorsForFiles [ "src/M3e.elm", "../src/M3e.elm" ]



-- COMMON ---------------------------------------------------------------------


common : List Rule
common =
    [ NoExposingEverything.rule |> ignoreVendor

    -- `M3e` is whitelisted: the top-level facade is purpose-built for
    -- `import M3e exposing (..)` (the single-import goal of facade epic #52).
    , NoImportingEverything.rule [ "M3e" ] |> ignoreVendor
    , NoMissingTypeAnnotation.rule |> ignoreVendor
    , NoMissingTypeAnnotationInLetIn.rule |> ignoreVendor
    , NoMissingTypeExpose.rule |> ignoreVendor |> ignorePublicApi |> ignoreRouteModules
    , NoConfusingPrefixOperator.rule
    , NoPrematureLetComputation.rule
    ]



-- DOCS -----------------------------------------------------------------------


docs : List Rule
docs =
    [ Docs.ReviewAtDocs.rule |> ignoreVendor
    , Docs.ReviewLinksAndSections.rule |> ignoreVendor
    , Docs.UpToDateReadmeLinks.rule |> ignoreVendor
    ]



-- CORRECTNESS (run on vendor too) --------------------------------------------


correctness : List Rule
correctness =
    [ Simplify.rule Simplify.defaults
    , NoDebug.Log.rule
    , NoDebug.TodoOrToString.rule
    ]



-- MATERIAL DISCIPLINE (custom MISI rules) ------------------------------------


{-| Ui-era material-discipline rules that the facts-driven rules made obsolete were retired
(docs/DESIGN.md §5): `NoUntypedSlot` (phantom-typed slots enforce it at compile time),
`NoRawAttributeInUi` + `NoRawLayoutOutsideLayoutModule` (both generic into the
configurable `NoSeamOutsideAllowedModules`), `PreferBadgeCount` (`M3e.Badge` has no
`count`/`label`), and `NoMissingFacadeEntry` (the facade epic #52 is closed).

`NoProprietaryDsClasses` survives unchanged — it still inspects `Attr.class` string
literals for proprietary `ds-`/`t-` tokens.

Opinion-leak audit (the "packages stay unopinionated about seam/kit content"
principle that retired `NoActionlessButton`): `NoProprietaryDsClasses` is a
CORRECTNESS check, not a content opinion. A `ds-`/`t-` class renders nothing in
this component system, so flagging it catches dead markup — it does not dictate
what a seam or kit may contain. It stays. The structural boundary rules
(`NoSeamOutsideAllowedModules`, `NoInternalImportOutsideAllowed`, the `toHtml`
gate) likewise enforce WHERE crossings live, not WHAT they contain, so they are
in-bounds too.

-}
materialDiscipline : List Rule
materialDiscipline =
    [ NoProprietaryDsClasses.rule
    ]


{-| The facts-driven, namespace-agnostic rules (docs/DESIGN.md §5), sourced from
the sibling `jackhp95/elm-review-cem` package. They read the generated
`M3e.Review.Facts.facts`, so a `@m3e/web` bump only regenerates the facts — the
rule logic (which lives in the package) is unchanged.

This is `Cem.all`'s rule set (ValidEnumValue, RequireSlot, SingularSlot,
SingularAttribute, MissingRequiredAttribute, MissingRequiredSingularSlot,
ValidSlotKind at the `Lenient` posture) with ONE deliberate swap: **`preferBarrel`
in place of `preferComponentModules`**. So the whole codebase — the generated library,
the docs app, and the Guide — defaults to the one-import **barrel, loose**
form (`M3e.button [ M3e.variantFilled ] [ … ]`) rather than the per-component
`M3e.<Component>` modules. The two are proven inverses, so `elm-review --fix`
migrates either direction. The five `Cem.translateTo*` layer/form translators stay
opt-in (used ad hoc by the `docs/scripts/examples-gen` harness, not here).

The seam gate (`NoSeamOutsideAllowedModules`) and the opaque-IR backstop
(`NoInternalImportOutsideAllowed`) are the M3e-specific rules; they arrive via
`CodegenReviewConfig.config`, which is concatenated into `config` below. The docs app's Tailwind/raw-HTML crossings are centralised in its
designated adapters (`Layout`, `Kit`, `Native`, `Doc`, `Shared`), which are on
that rule's allow-list, so feature routes stay seam-free (docs/DESIGN.md §4, #81).

TODO: `jackhp95/elm-review-cem` is not yet published to the Elm registry, so its
rules are pulled in via the `../../elm-review-cem/src` source-directory in
`review/elm.json` (the sibling repo must be checked out alongside `elm-m3e`). Swap
that for a published `jackhp95/elm-review-cem` dependency once it is on the registry.

-}
codegenAware : List Rule
codegenAware =
    let
        facts =
            M3e.Review.Facts.facts

        -- The generated library is machine-emitted; the barrel module's own
        -- `foo = M3e.Foo.view` re-exports would otherwise trip `preferBarrel` on
        -- itself. These usage rules only make sense on consumer code.
        onConsumerCode : Rule -> Rule
        onConsumerCode =
            Rule.ignoreErrorsForDirectories [ "src/M3e/", "../src/M3e/" ]
                >> Rule.ignoreErrorsForFiles [ "src/M3e.elm", "../src/M3e.elm" ]

        -- `preferBarrel` is a LAYER/FORM PREFERENCE, not a correctness rule, so it
        -- exempts what the facts-derived correctness rules do not: the hand-written
        -- seam adapters (`Layout`, `Kit`, `Native`, `Doc`, `Shared` — the DESIGN §4
        -- allow-list), which deliberately hold the tight component-module form, so
        -- barrelising them is wrong by design (and several never import the `M3e`
        -- barrel at all). Every other codegen-aware rule stays on everywhere — they
        -- enforce facts-derived correctness that holds on every layer/form. Two path
        -- forms per entry cover root- vs `docs/`-relative review runs.
        onBarrelPreferredCode : Rule -> Rule
        onBarrelPreferredCode =
            onConsumerCode
                >> Rule.ignoreErrorsForDirectories
                    [ "kit/", "docs/kit/" ]
                >> Rule.ignoreErrorsForFiles
                    [ "src/Doc.elm"
                    , "docs/src/Doc.elm"
                    , "src/Layout.elm"
                    , "docs/src/Layout.elm"
                    , "app/Shared.elm"
                    , "docs/app/Shared.elm"
                    ]

        -- `preferComponentSetters` upgrades a GENERIC barrel slot
        -- (`M3e.slotLeading`) to the component setter (`M3e.listItemSlotLeading`)
        -- for compile-time slot-kind safety — the precise form real feature code
        -- should use. It carries every `onBarrelPreferredCode` exemption PLUS the
        -- **Guide**: the Guide walkthrough is the one place we KEEP the loose
        -- generic barrel. This exemption is PEDAGOGICAL, not an oversight —
        -- the Guide must keep compiling in the taught (generic) form so the
        -- tooling chapter's autofix demo (`/guide/tooling-refactors`) stays a real,
        -- runnable example of this rule upgrading that code to the precise form.
        -- Do not remove it. Everywhere else the precise form is enforced.
        onComponentSetterCode : Rule -> Rule
        onComponentSetterCode =
            onBarrelPreferredCode
                >> Rule.ignoreErrorsForDirectories [ "app/Route/Guide/", "docs/app/Route/Guide/" ]
                >> Rule.ignoreErrorsForFiles [ "app/Route/Guide.elm", "docs/app/Route/Guide.elm" ]
    in
    List.map onConsumerCode
        [ Cem.validEnumValue facts
        , Cem.requireSlot facts
        , Cem.singularSlot facts
        , Cem.singularAttribute facts
        , Cem.missingRequiredAttribute facts
        , Cem.missingRequiredSingularSlot facts
        , Cem.validSlotKindWith Cem.Lenient facts
        ]
        ++ [ onBarrelPreferredCode (Cem.preferBarrel facts)
           , onComponentSetterCode (Cem.preferComponentSetters facts)
           ]



-- CODE STYLE -----------------------------------------------------------------


{-| Code-style rules from `jfmengels/elm-review-code-style`.

  - `NoSimpleLetBody` — a let whose body is just a reference to its last
    binding is redundant; the binding can inline directly. Auto-fixable.
  - `NoUnnecessaryTrailingUnderscore` — trailing underscores on names that
    don't shadow anything are noise. Auto-fixable.
  - `NoRedundantlyQualifiedType` — `Set.Set`, `Dict.Dict` etc. can be written
    as just `Set`, `Dict` when the type is already in scope. Auto-fixable.

`NoModuleOnExposedNames` from `sparksp/elm-review-imports` — if a name is
already exposed on import, calling it via the module alias is redundant. Auto-fixable.

All four rules are ignored for generated dirs (vendor + .elm-pages).

-}
codeStyle : List Rule
codeStyle =
    [ NoSimpleLetBody.rule |> ignoreGenerated
    , NoUnnecessaryTrailingUnderscore.rule |> ignoreGenerated
    , NoRedundantlyQualifiedType.rule |> ignoreGenerated
    , NoModuleOnExposedNames.rule |> ignoreGenerated
    ]



-- COGNITIVE COMPLEXITY -------------------------------------------------------


{-| Flag functions with a cognitive complexity score above 15. Study routes
(Rally, Shrine, Crane, Name\_) are intentionally complex; their findings go
into the suppression baseline rather than forcing a refactor. Generated dirs
are ignored.
-}
complexity : List Rule
complexity =
    [ CognitiveComplexity.rule 15 |> ignoreGenerated
    ]



-- toHtml GATE ----------------------------------------------------------------


{-| `M3e.Node.toHtml` is the single escape hatch from the Node IR to Html. It
must only be called from `Shared` (the one place the app assembles a real
Html.Html tree) and from within `M3e.Node` itself (for the recursive traversal).

A violation here means a route or helper is bypassing the IR — that is a real
regression, not legacy debt, and must NOT be suppressed.

The test suite (which lives in `../tests/` relative to docs/elm.json) calls
`Node.toHtml` to produce `Html` values for assertion; those are acceptable.
Because the review is run from `docs/` the path prefix is `../tests/`.

-}
toHtmlGate : List Rule
toHtmlGate =
    [ NoFunctionOutsideOfModules.rule
        [ ( [ "M3e.Node.toHtml" ], [ "Shared", "M3e.Node" ] ) ]
        |> Rule.ignoreErrorsForDirectories [ "../tests/", "tests/" ]
    ]
