module ReviewConfig exposing (config)

{-| The elm-review configuration for the `M3e` generated component library and
the `docs/` application.

The library lives in `src/*` (generated by `elm-cem`); the docs app
lives in `docs/app/`. This config is run from `docs/` against `docs/elm.json`
(whose source-dirs cover `app`, `src`, `.elm-pages`, `../src`, and the
vendored `vendor/elm-foundation`) via:

    cd docs && node_modules /. bin / elm - review --config ../review --compiler node_modules/.bin/elm

See `review/README.md` for the rationale behind each rule and every relaxation.

-}

import Cem
import CodegenReviewConfig
import CognitiveComplexity
import Docs.ReviewAtDocs
import Docs.ReviewLinksAndSections
import Docs.UpToDateReadmeLinks
import M3e.Review.Facts
import NoConfusingPrefixOperator
import NoDebug.Log
import NoDebug.TodoOrToString
import NoExposingEverything
import NoFunctionOutsideOfModules
import NoImportingEverything
import NoMissingComponentApiNames
import NoMissingTypeAnnotation
import NoMissingTypeAnnotationInLetIn
import NoMissingTypeExpose
import NoModuleOnExposedNames
import NoPrematureLetComputation
import NoProprietaryDsClasses
import NoRedundantlyQualifiedType
import NoSimpleLetBody
import NoUnnecessaryTrailingUnderscore
import NoUnused.CustomTypeConstructorArgs
import NoUnused.CustomTypeConstructors
import NoUnused.Exports
import NoUnused.Modules
import NoUnused.Parameters
import NoUnused.Patterns
import NoUnused.Variables
import Review.Rule as Rule exposing (Rule)
import Simplify


config : List Rule
config =
    (List.concat
        [ unused
        , common
        , docs
        , correctness
        , materialDiscipline
        , codegenAware
        , CodegenReviewConfig.config
        , codeStyle
        , complexity
        , toHtmlGate
        ]
        |> List.map (ignoreElmPages >> ignoreLibraryTests >> ignoreGeneratedSubstrate >> ignoreGeneratedComposeAttrs)
    )
        -- `NoMissingComponentApiNames` is the one rule that must run ON the
        -- generated library (`src/M3e/Component/*`) — it guards that every
        -- generated component module exposes its `<name>`/`required` constructors.
        -- So it is deliberately EXEMPT from `ignoreGeneratedSubstrate` (which
        -- otherwise hides `../src/` when review runs from `docs/`). It self-scopes
        -- to `M3e.Component.*` modules, so it is a no-op on the docs app.
        ++ [ NoMissingComponentApiNames.rule { componentNamespace = [ "M3e", "Component" ] } ]


{-| The generated brand surfaces, the IR, and the vendored foundation copies
are regenerated wholesale (the regen-diff gates own their hygiene) — style rules
must not lint them. The cem discipline rules check CALL SITES in app code, so
nothing load-bearing is lost.

`vendor/` holds the `HtmlIr.*` and `TypedHtml.*` sources vendored for
self-contained Netlify builds (commit 0c93150); they are byte-identical copies
of `../../elm-html-intermediate-representation/src` and `../../elm-typed-html/src`,
which are already excluded via the sibling paths below. Two path forms cover the
vendored copies regardless of working directory:
`vendor/elm-foundation/` (from docs/) and `../docs/vendor/elm-foundation/` (from repo root).

-}
ignoreGeneratedSubstrate : Rule -> Rule
ignoreGeneratedSubstrate =
    Rule.ignoreErrorsForDirectories
        [ "../src/"
        , "../../elm-typed-html/src/"
        , "../../elm-html-intermediate-representation/src/"
        , "../../elm-cem/facts/src/"
        , "../../elm-cem-compose/src/"
        , "../../elm-cem-compose/tests/src/"
        , "vendor/elm-foundation/"
        , "../docs/vendor/elm-foundation/"
        ]


{-| `Attrs.elm` is derived by `scripts/gen-compose-attrs.mjs` from
`M3e.Attributes`/`M3e.Review.Facts` (`npm run check:compose-attrs` is what
gates its hygiene, by byte-comparing against a fresh regeneration — never
hand-edit it). Its `witness` export exists ONLY to make a renamed/retired
setter a compile error and is deliberately never imported anywhere, so
NoUnused-family rules would flag exactly the thing that makes it useful.
Excluded by FILE, not by directory: `Render`/`Codegen`/other hand-written
modules under `Compose/` stay fully reviewed. Two path forms cover root- vs
docs/-relative runs.
-}
ignoreGeneratedComposeAttrs : Rule -> Rule
ignoreGeneratedComposeAttrs =
    Rule.ignoreErrorsForFiles
        [ "app/Compose/Attrs.elm"
        , "docs/app/Compose/Attrs.elm"
        ]


{-| `.elm-pages/` is fully generated routing/metadata — NO rule should lint it.
Applied to EVERY rule here so generated routing code never enters the suppression
baseline.
-}
ignoreElmPages : Rule -> Rule
ignoreElmPages =
    Rule.ignoreErrorsForDirectories [ ".elm-pages/" ]


{-| The `tests/` project holds the library's own tests: `tests/tests/`
(`DomOutputTest` — an elm-test unit suite that legitimately imports the opaque-IR
interiors and uses `Seam` to construct fixtures). None of it is docs-app source,
so it is not gated by the docs review — ignore the whole `tests/` tree for EVERY
rule. Two path forms cover root- vs docs/-relative runs.
-}
ignoreLibraryTests : Rule -> Rule
ignoreLibraryTests =
    Rule.ignoreErrorsForDirectories [ "tests/", "../tests/" ]


{-| `src/` is entirely generated by `elm-cem` (the typed component
library plus its verbatim runtime templates). Style and documentation rules
should not gate on generated code; correctness rules (`Simplify`, `NoDebug.*`,
and the Material-discipline rules) still run on it.

Two path forms: `"src/"` (from repo root) and
`"../src/"` (from docs/, whose elm.json lists `../src`
as a source directory). Both are present so the ignore works regardless of the
working directory the review runs from.

-}
ignoreVendor : Rule -> Rule
ignoreVendor rule =
    rule
        |> Rule.ignoreErrorsForDirectories [ "src/M3e/", "../src/M3e/" ]
        |> Rule.ignoreErrorsForFiles [ "src/M3e.elm", "../src/M3e.elm" ]


{-| `.elm-pages/` contains auto-generated routing and metadata. Treat it the
same as the generated `src/` library — correctness rules still run,
style rules do not.
-}
ignoreGenerated : Rule -> Rule
ignoreGenerated rule =
    rule
        |> Rule.ignoreErrorsForDirectories [ "src/M3e/", "../src/M3e/", ".elm-pages/" ]
        |> Rule.ignoreErrorsForFiles [ "src/M3e.elm", "../src/M3e.elm" ]



-- UNUSED ---------------------------------------------------------------------


unused : List Rule
unused =
    [ NoUnused.Variables.rule |> ignoreGenerated
    , NoUnused.CustomTypeConstructors.rule [] |> ignoreGenerated |> ignorePublicApi |> ignoreElmPagesUserModules
    , NoUnused.CustomTypeConstructorArgs.rule |> ignoreGenerated
    , NoUnused.Exports.rule |> ignoreGenerated |> ignorePublicApi |> ignoreElmPagesUserModules
    , NoUnused.Modules.rule |> ignoreGenerated |> ignorePublicApi
    , NoUnused.Parameters.rule |> ignoreGenerated
    , NoUnused.Patterns.rule |> ignoreGenerated
    ]


{-| `app/Effect.elm` and `app/View.elm` are the elm-pages "user-owned" framework
modules. The framework wires them through generated code in `.elm-pages/` (which
every rule already ignores), so `elm-review` — which only sees the app source —
reads their framework-contract surface as unused:

  - `Effect`'s `Submit`/`SubmitFetcher`/`SetField`/`FetchRouteData` constructors and
    the `Effect(..)` export back `perform`'s helper record, which generated `Main`
    builds and calls; they are the standard elm-pages form/fetcher effect scaffold,
    live-by-contract even when no current page submits a form.
  - `testPerform` is the required companion to `perform` for the `Test.PagesProgram`
    harness.
  - `View`'s `freeze`/`freezableToHtml`/`htmlToFreezable` are the frozen-view
    build-time-render + client-adoption seam, transformed by a codemod (see the
    module docs) — deliberate infra, not dead code.

Exempt both files from the unused-export/constructor rules (config-level intent,
not a suppression-baseline debt). Two path forms cover root- vs docs/-relative runs.

-}
ignoreElmPagesUserModules : Rule -> Rule
ignoreElmPagesUserModules =
    Rule.ignoreErrorsForFiles
        [ "app/Effect.elm", "docs/app/Effect.elm", "app/View.elm", "docs/app/View.elm" ]


{-| `NoMissingTypeExpose` is a package-API rule: "an exposed function's signature
mentions a private type, so a consumer could not name it." elm-pages `Route`
modules are application code — nothing imports them except generated glue, and the
exposed `route` value's signature necessarily mentions the module-private
`RouteParams` (plus page-local data types like `Component`/`UsageExample`).
Exposing those would be meaningless ceremony, so relax the rule for `app/Route/`.
Two path forms cover root- vs docs/-relative runs.
-}
ignoreRouteModules : Rule -> Rule
ignoreRouteModules =
    Rule.ignoreErrorsForDirectories [ "app/Route/", "docs/app/Route/" ]


{-| A published library's whole point is exports/modules/constructors that are
unused _by itself_ — every `M3e.*` value and every exposed `Variant(..)`-style
constructor exists for consumers we cannot see in this repo.

Reviewing the library in isolation (no docs app, no consuming app) makes
`NoUnused.Exports`, `NoUnused.Modules`, and `NoUnused.CustomTypeConstructors`
fire on the entire public API. We ignore the generated `src/M3e/`
directory (and the top-level `src/M3e.elm` barrel, whose re-exports
are unused-by-self until consumers import them) for those rules so they still
catch genuinely-dead code in any non-public helper directories while leaving the
public surface alone.

`NoMissingTypeExpose` is relaxed here for the same directory: the generated
phantom-typed API deliberately keeps some infra types private, which the rule
reads as a "private type used by an exposed type".

Two path forms are listed: `"src/M3e/"` (when review runs from the
repo root) and `"../src/M3e/"` (when it runs from `docs/`, whose
elm.json lists `../src` as a source directory). Both must be present
so that the ignore works regardless of working directory.

-}
ignorePublicApi : Rule -> Rule
ignorePublicApi rule =
    rule
        |> Rule.ignoreErrorsForDirectories [ "src/M3e/", "../src/M3e/" ]
        |> Rule.ignoreErrorsForFiles [ "src/M3e.elm", "../src/M3e.elm" ]



-- COMMON ---------------------------------------------------------------------


common : List Rule
common =
    [ NoExposingEverything.rule |> ignoreVendor

    -- `M3e` is whitelisted: the top-level facade is purpose-built for
    -- `import M3e exposing (..)` (the single-import goal of facade epic #52).
    , NoImportingEverything.rule [ "M3e" ] |> ignoreVendor
    , NoMissingTypeAnnotation.rule |> ignoreVendor
    , NoMissingTypeAnnotationInLetIn.rule |> ignoreVendor
    , NoMissingTypeExpose.rule |> ignoreVendor |> ignorePublicApi |> ignoreRouteModules
    , NoConfusingPrefixOperator.rule
    , NoPrematureLetComputation.rule
    ]



-- DOCS -----------------------------------------------------------------------


docs : List Rule
docs =
    [ Docs.ReviewAtDocs.rule |> ignoreVendor
    , Docs.ReviewLinksAndSections.rule |> ignoreVendor
    , Docs.UpToDateReadmeLinks.rule |> ignoreVendor
    ]



-- CORRECTNESS (run on vendor too) --------------------------------------------


correctness : List Rule
correctness =
    [ Simplify.rule Simplify.defaults
    , NoDebug.Log.rule
    , NoDebug.TodoOrToString.rule
    ]



-- MATERIAL DISCIPLINE (custom MISI rules) ------------------------------------


{-| Ui-era material-discipline rules that the facts-driven rules made obsolete were retired
(docs/DESIGN.md §5): `NoUntypedSlot` (phantom-typed slots enforce it at compile time),
`NoRawAttributeInUi` + `NoRawLayoutOutsideLayoutModule` (both generic into the
configurable `NoSeamOutsideAllowedModules`), `PreferBadgeCount` (`M3e.Badge` has no
`count`/`label`), and `NoMissingFacadeEntry` (the facade epic #52 is closed).

`NoProprietaryDsClasses` was **strengthened** from "no `ds-`/`t-` tokens" into the
full **layout-only** classifier: Tailwind may position, size and space, but every
painting utility — background, colour, border, radius, elevation/shadow,
typography — is an error, because styling belongs to an m3e component. It also
resolves `class` through `TypedHtml.Attributes`, `M3e.Attributes` and
`Svg.Attributes` on top of `Html.Attributes`; resolving only the last left it
toothless on this docs app, where 503 of 591 class call sites go through
`TypedHtml.Attributes`. See the rule's own docs for the three-bucket
classification (proprietary / styling / allowed) and why unknown tokens are
allowed by default.

Opinion-leak audit (the "packages stay unopinionated about seam/kit content"
principle that retired `NoActionlessButton`): the proprietary half is a
CORRECTNESS check — a `ds-`/`t-` class renders nothing in this component system,
so flagging it catches dead markup. The layout-only half is a stated PROJECT
POLICY, and it is scoped accordingly: it polices the docs app's own surfaces, not
what a seam or kit may contain. The structural boundary rules
(`NoSeamOutsideAllowedModules`, `NoInternalImportOutsideAllowed`, the `toHtml`
gate) likewise enforce WHERE crossings live, not WHAT they contain, so they are
in-bounds too.

**`Route/Styles/` is exempt.** Those pages apply token utilities as LIVE
SPECIMENS — a typography page whose job is to show what `text-body-lg` renders has
to actually apply `text-body-lg`. Linting them would delete the documentation of a
real feature rather than fix a styling mistake. The exemption is per-directory, so
it necessarily also lifts the proprietary-token check there; acceptable because
those pages carry no `ds-`/`t-` tokens, and splitting the rule in two to recover it
would buy nothing today.

`Route/Guide/Theming.elm` was exempt too and **is not any more.** It was exempt on
the theory that it "teaches the Tailwind bridge by demonstrating it" — but what it
actually taught was the anti-pattern: it presented `bg-primary text-on-primary` and
`rounded-md-corner-large` as _the right move_, and its "Paint with roles, not hex"
section demonstrated colour roles as `class` tokens on bare `<div>`s. The exemption
was hiding a page that contradicted the policy the rest of the app is held to. The
prose now teaches the real order (component → its attributes/slots → its own `m3e-*`
property → file a gap), its wrong-example blocks are string literals the rule
correctly ignores, and its live `class` calls are layout-only — so it passes on its
own merits and needs no exemption.

-}
materialDiscipline : List Rule
materialDiscipline =
    [ NoProprietaryDsClasses.rule [ "Seam" ]
        |> Rule.ignoreErrorsForDirectories
            [ "app/Route/Styles/", "docs/app/Route/Styles/" ]
        -- The theme editor's own live previews, exempt for exactly the same
        -- reason as `Route/Styles/`: the swatch that shows you which corner
        -- radius you just picked has to APPLY that radius, and the type-scale
        -- preview has to apply the computed font size. They are specimens of
        -- the token being edited, not surfaces that forgot to use a component.
        |> Rule.ignoreErrorsForFiles
            [ "app/Theme/Sections/Shape.elm"
            , "docs/app/Theme/Sections/Shape.elm"
            , "app/Theme/Sections/Typography.elm"
            , "docs/app/Theme/Sections/Typography.elm"
            ]
    ]


{-| The facts-driven, namespace-agnostic rules (docs/DESIGN.md §5), sourced from
the sibling `jackhp95/elm-review-cem` package. They read the generated
`M3e.Review.Facts.facts`, so a `@m3e/web` bump only regenerates the facts — the
rule logic (which lives in the package) is unchanged.

This is `Cem.all`'s rule set (ValidEnumValue, RequireSlot, SingularSlot,
SingularAttribute, MissingRequiredAttribute, MissingRequiredSingularSlot,
ValidSlotKind at the `Lenient` posture) with ONE deliberate swap: **`preferBarrel`
in place of `preferComponentModules`**. So the whole codebase — the generated library,
the docs app, and the Guide — defaults to the one-import **barrel, loose**
form (`M3e.button [ M3e.variantFilled ] [ … ]`) rather than the per-component
`M3e.<Component>` modules. The two are proven inverses, so `elm-review --fix`
migrates either direction. The five `Cem.translateTo*` layer/form translators stay
opt-in (used ad hoc by the `docs/scripts/examples-gen` harness, not here).

The seam gate (`NoSeamOutsideAllowedModules`) and the opaque-IR backstop
(`NoInternalImportOutsideAllowed`) are the M3e-specific rules; they arrive via
`CodegenReviewConfig.config`, which is concatenated into `config` below.

NOTE: this paragraph used to claim the docs app centralises its crossings in
"designated adapters (`Layout`, `Kit`, `Native`, `Doc`, `Shared`)". That was
false on two counts — `Layout`, `Kit` and `Native` do not exist as modules, and
they were never on that rule's allow-list either. Only `Doc` and `Shared` are
real. The single designated destination is now `Seam`, named consistently by
both this rule and `NoSeamOutsideAllowedModules`; it is not created until
something genuinely needs containing (docs/DESIGN.md §4, #81).

TODO: `jackhp95/elm-review-cem` is not yet published to the Elm registry, so its
rules are pulled in via the `../../elm-review-cem/src` source-directory in
`review/elm.json` (the sibling repo must be checked out alongside `elm-m3e`). Swap
that for a published `jackhp95/elm-review-cem` dependency once it is on the registry.

-}
codegenAware : List Rule
codegenAware =
    let
        facts =
            M3e.Review.Facts.facts

        -- The generated library is machine-emitted; the barrel module's own
        -- `foo = M3e.Foo.view` re-exports would otherwise trip `preferBarrel` on
        -- itself. These usage rules only make sense on consumer code.
        onConsumerCode : Rule -> Rule
        onConsumerCode =
            Rule.ignoreErrorsForDirectories [ "src/M3e/", "../src/M3e/" ]
                >> Rule.ignoreErrorsForFiles [ "src/M3e.elm", "../src/M3e.elm" ]

        -- `preferBarrel` is a LAYER/FORM PREFERENCE, not a correctness rule, so it
        -- exempts what the facts-derived correctness rules do not: the hand-written
        -- seam adapters (`Doc`, `Shared` — the real DESIGN §4 allow-list; `Layout`,
        -- `Kit`, `Native` never existed, see the NOTE above), which deliberately hold the tight component-module form, so
        -- barrelising them is wrong by design (and several never import the `M3e`
        -- barrel at all). Every other codegen-aware rule stays on everywhere — they
        -- enforce facts-derived correctness that holds on every layer/form. Two path
        -- forms per entry cover root- vs `docs/`-relative review runs.
        onBarrelPreferredCode : Rule -> Rule
        onBarrelPreferredCode =
            onConsumerCode
                >> Rule.ignoreErrorsForFiles
                    [ "src/Doc.elm"
                    , "docs/src/Doc.elm"
                    , "app/Shared.elm"
                    , "docs/app/Shared.elm"
                    ]

        -- `preferComponentSetters` upgrades a GENERIC barrel slot
        -- (`M3e.slotLeading`) to the component setter (`M3e.listItemSlotLeading`)
        -- for compile-time slot-kind safety — the precise form real feature code
        -- should use. It carries every `onBarrelPreferredCode` exemption PLUS the
        -- **Guide**: the Guide walkthrough is the one place we KEEP the loose
        -- generic barrel. This exemption is PEDAGOGICAL, not an oversight —
        -- the Guide must keep compiling in the taught (generic) form so the
        -- tooling chapter's autofix demo (`/guide/tooling-refactors`) stays a real,
        -- runnable example of this rule upgrading that code to the precise form.
        -- Do not remove it. Everywhere else the precise form is enforced.
        onComponentSetterCode : Rule -> Rule
        onComponentSetterCode =
            onBarrelPreferredCode
                >> Rule.ignoreErrorsForDirectories [ "app/Route/Guide/", "docs/app/Route/Guide/" ]
                >> Rule.ignoreErrorsForFiles [ "app/Route/Guide.elm", "docs/app/Route/Guide.elm" ]
    in
    List.map onConsumerCode
        [ Cem.validEnumValue facts
        , Cem.requireSlot facts
        , Cem.singularSlot facts
        , Cem.singularAttribute facts
        , Cem.missingRequiredAttribute facts
        , Cem.missingRequiredSingularSlot facts
        , Cem.validSlotKindWith Cem.Lenient facts
        ]
        ++ [ onBarrelPreferredCode (Cem.preferBarrel facts)
           , onComponentSetterCode (Cem.preferComponentSetters facts)
           ]



-- CODE STYLE -----------------------------------------------------------------


{-| Code-style rules from `jfmengels/elm-review-code-style`.

  - `NoSimpleLetBody` — a let whose body is just a reference to its last
    binding is redundant; the binding can inline directly. Auto-fixable.
  - `NoUnnecessaryTrailingUnderscore` — trailing underscores on names that
    don't shadow anything are noise. Auto-fixable.
  - `NoRedundantlyQualifiedType` — `Set.Set`, `Dict.Dict` etc. can be written
    as just `Set`, `Dict` when the type is already in scope. Auto-fixable.

`NoModuleOnExposedNames` from `sparksp/elm-review-imports` — if a name is
already exposed on import, calling it via the module alias is redundant. Auto-fixable.

All four rules are ignored for generated dirs (vendor + .elm-pages).

-}
codeStyle : List Rule
codeStyle =
    [ NoSimpleLetBody.rule |> ignoreGenerated
    , NoUnnecessaryTrailingUnderscore.rule |> ignoreGenerated
    , NoRedundantlyQualifiedType.rule |> ignoreGenerated
    , NoModuleOnExposedNames.rule |> ignoreGenerated
    ]



-- COGNITIVE COMPLEXITY -------------------------------------------------------


{-| Flag functions with a cognitive complexity score above 15. Study routes
(Rally, Shrine, Crane, Name\_) are intentionally complex; their findings go
into the suppression baseline rather than forcing a refactor. Generated dirs
are ignored.
-}
complexity : List Rule
complexity =
    [ CognitiveComplexity.rule 15 |> ignoreGenerated
    ]



-- toHtml GATE + THE RECAST FENCE ----------------------------------------------


{-| `M3e.Node.toHtml` is the single escape hatch from the Node IR to Html. It
must only be called from `Shared` (the one place the app assembles a real
Html.Html tree) and from within `M3e.Node` itself (for the recursive traversal).

A violation here means a route or helper is bypassing the IR — that is a real
regression, not legacy debt, and must NOT be suppressed.

The test suite (which lives in `../tests/` relative to docs/elm.json) calls
`Node.toHtml` to produce `Html` values for assertion; those are acceptable.
Because the review is run from `docs/` the path prefix is `../tests/`.


## The recast fence

`recast` / `recastAll` / `recastAttr` / `recastAttrAll` re-kind an element or
attribute by throwing away its phantom rows, so anything drops into any slot.
They exist for CONSUMERS who deliberately deviate from Material patterns and want
their deviations to stay internally consistent. **This docs app sticks to standard
Material, so it should never need one** — a recast here means one of exactly two
things, and both are bugs with a real fix:

1.  a **codegen-config failure** — a slot in `config/slots.json` is declared with
    the wrong kinds, so the generated type is wrong; or
2.  **invalid markup** — the page is putting content somewhere Material does not
    put it.

That is not a theory. The docs app's only two recast call sites were both in
`Shared.sectionPanel`, and they were case 1: the expansion panel's `header` slot
was declared `"kinds": ["any"]`, identical to its `unnamed` slot, so codegen gave
both the SAME type variable and forced the header and body to unify. Fixing the
config to `["expansionHeader"]` made both escapes evaporate. The count is now
ZERO, which is why there is no `Seam` module to centralise into — there is
nothing left to centralise, and an empty designated module would be worse than
none.

So the fence allows these functions **only in the library module that defines
them**. If this rule ever fires, do not add the calling module to the allow-list:
find out which of the two causes above it is and fix that instead.

-}
toHtmlGate : List Rule
toHtmlGate =
    [ NoFunctionOutsideOfModules.rule
        [ ( [ "M3e.Node.toHtml" ], [ "Shared", "M3e.Node" ] )
        , ( [ "M3e.Unsafe.recast", "M3e.Unsafe.recastAll" ], [ "M3e.Unsafe" ] )
        , ( [ "M3e.Unsafe.Attributes.recastAttr", "M3e.Unsafe.Attributes.recastAttrAll" ]
          , [ "M3e.Unsafe.Attributes" ]
          )
        ]
        |> Rule.ignoreErrorsForDirectories [ "../tests/", "tests/" ]
    ]
