module Sample.ToolingRefactors.ConvertBefore exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.ToolingRefactors.convertBefore`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Component.Button
import M3e.Values as Value


-- the per-component surface — what you might write, or arrive with
shown0_ =
    M3e.Component.Button.view [ M3e.Component.Button.variant Value.filled ] [ M3e.text "Save" ]
