module Sample.ToolingRefactors.ConvertAfter exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.ToolingRefactors.convertAfter`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Action
import M3e.Attributes
import M3e.Component.Button
import M3e.Values as Value


-- after autofix: the pinned form — one import, the shared vocabulary
shown0_ =
    M3e.Component.Button.component { content = M3e.text "Save", action = M3e.Action.none } [ M3e.Attributes.variant Value.filled ] []
