module Sample.ToolingRefactors.ExtractAfter exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.ToolingRefactors.extractAfter`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import TypedHtml
import TypedHtml.Attributes


-- after autofix: the typed setter, no escape at all
shown0_ =
    M3e.button [ TypedHtml.Attributes.class "flex-auto" ] [ M3e.text "Save" ]
