module Sample.InvalidStates.BrokenCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.InvalidStates.brokenCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Action
import M3e.Attributes
import M3e.Component.Button
import M3e.Values as Value


shown0_ =
    M3e.button { content = M3e.Component.Button.icon (M3e.chip { content = M3e.text "not an icon" } [] []), action = M3e.Action.none } [ M3e.Attributes.variant Value.filled ] [ M3e.text "Save" ]
