module Sample.Theming.BridgeCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Theming.bridgeCode`, compiled for real.
Change the sample there; this file follows.

-}

import Sample.Support exposing (rows)
import TypedHtml
import TypedHtml.Attributes


-- GOOD: layout via utility classes; surface + shape + color via M3 token classes.
shown0_ =
    TypedHtml.div
        [ TypedHtml.Attributes.class "bg-surface-container rounded-md-corner-large"
        , TypedHtml.Attributes.class "overflow-hidden flex flex-col"
        ]
        rows


-- WRONG: a raw corner and a raw color doing a token's job — adrift from the
-- shape scale, and wrong the moment the scheme flips.
shown1_ =
    TypedHtml.div [ TypedHtml.Attributes.class "rounded-3xl bg-[#4285F4] p-4" ] rows
