module Sample.Theming.DarkCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Theming.darkCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Component.Theme as Theme
import M3e.Values
import Sample.Support exposing (model)


-- Light/dark is one input, held in the model and flipped:
shown0_ =
    Theme.scheme (if model.dark then M3e.Values.dark else M3e.Values.light)


-- Dynamic color is one input too — a new seed re-derives every role:
shown1_ =
    Theme.color model.brandSeed
