module Sample.Theming.ReskinCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Theming.reskinCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Theme as Theme
import M3e.Values
import Sample.Support exposing (appBody)


-- Before: the default seed, standard density, default corners.
shown0_ =
    Theme.view
        [ Theme.color "#4285F4"
        , Theme.scheme M3e.Values.light
        , Theme.density 0
        ]
        [ appBody ]


-- After: a brand re-skin. New seed re-derives the ENTIRE palette;
-- density and corner language shift globally. appBody is untouched.
shown1_ =
    Theme.view
        [ Theme.color "#6750A4"          -- brand accent — every role re-derives
        , Theme.scheme M3e.Values.light
        , Theme.contrast M3e.Values.medium -- a touch more contrast for the new palette
        , Theme.density -1                 -- slightly more compact
        ]
        -- Shapes are not a Theme input: set the corner where the surface is built,
        -- e.g. TA.class "rounded-md-corner-large" on that surface.
        [ appBody ]
