module Sample.Theming.RolesCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Theming.rolesCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import Sample.Support exposing (children, href, rows)
import TypedHtml
import TypedHtml.Attributes


-- A selected row is a surface-ROLE swap, not a hand-picked color:
shown0_ =
    TypedHtml.div [ TypedHtml.Attributes.class "bg-surface-container" ] rows


shown1_ =
    TypedHtml.span [ TypedHtml.Attributes.class "text-body-lg text-on-surface-variant" ] [ M3e.text "Secondary text" ]


shown2_ =
    TypedHtml.a [ TypedHtml.Attributes.href href, TypedHtml.Attributes.class "text-primary" ] [ M3e.text "Primary action" ]


-- WRONG — a raw color, decoupled from the scheme, wrong in dark mode:
shown3_ =
    TypedHtml.div [ TypedHtml.Attributes.class "bg-[#4285F4] text-white" ] children
