module Sample.Theming.RolesCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Theming.rolesCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Attributes
import M3e.Component.ListItem
import M3e.Values
import Sample.Support exposing (children, rows)
import TypedHtml
import TypedHtml.Attributes


-- The container-surface role: a filled card. It paints its own background
-- AND its own foreground from the theme.
shown0_ =
    M3e.card [ M3e.Attributes.variant M3e.Values.filled ] rows


-- The de-emphasized role: a list item's own slot. Correct color and type
-- scale, no class involved.
shown1_ =
    M3e.listItem []
        [ M3e.text "Primary line"
        , M3e.Component.ListItem.supportingText (M3e.text "Secondary text")
        ]


-- The primary-action role: a filled button, with the state layer and focus
-- ring that come with it.
shown2_ =
    M3e.button [ M3e.Attributes.variant M3e.Values.filled ] [ M3e.text "Continue" ]


-- WRONG — the right ROLES, but hand-painted onto bare elements. Themed, and
-- still a card and a list item reimplemented in CSS: no state layer, no
-- density, no accessibility.
shown3_ =
    TypedHtml.div [ TypedHtml.Attributes.class "bg-surface-container" ] rows


shown4_ =
    TypedHtml.span [ TypedHtml.Attributes.class "text-body-lg text-on-surface-variant" ] [ M3e.text "Secondary text" ]


-- WRONG — a raw color, decoupled from the scheme, wrong in dark mode:
shown5_ =
    TypedHtml.div [ TypedHtml.Attributes.class "bg-[#4285F4] text-white" ] children
