module Sample.Theming.RootCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Theming.rootCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e.Component.Theme as Theme
import Sample.Support exposing (appBody, model)


shown0_ =
    Theme.theme
        [ Theme.color model.seed                    -- the brand/seed color, e.g. "#4285F4"
        , Theme.scheme model.scheme                 -- M3e.Values.light | M3e.Values.dark
        , Theme.contrast model.contrast             -- standard | medium | high
        , Theme.density model.density               -- 0 (default) down to -3 (compact)
        ]
        [ appBody ]
