module Sample.AccessibleByConstruction.NamelessCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.AccessibleByConstruction.namelessCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import TypedHtml.Attributes as TA


shown0_ =
    M3e.iconButton []
        [ M3e.icon [ TA.name "help" ] [] ]
