module M3e.Html.Heading exposing (heading, emphasized, level, size, variant, tocIgnore)

{-| Middle layer for `<m3e-heading>`: the phantom-typed `Attr` setters (each an OPEN capability row) and an eager component that evaluates them onto the bottom `elm/html` layer. This is the loose, escape-hatch form; prefer the strict `M3e.Heading` module for everyday use.

@docs heading, emphasized, level, size, variant, tocIgnore

-}

import Html
import M3e.Raw.Heading
import M3e.Token
import Markup.Html.Attr
import Markup.Html.Attr.Internal


{-| A heading to a page or section.

**Component Info:**

  - **Extends:** `LitElement`

-}
heading :
    List
        (Markup.Html.Attr.Attr
            { emphasized : M3e.Token.Supported
            , level : M3e.Token.Supported
            , size : M3e.Token.Supported
            , variant : M3e.Token.Supported
            , tocIgnore : M3e.Token.Supported
            , slot : M3e.Token.Supported
            }
            msg
        )
    -> List (Html.Html msg)
    -> Html.Html msg
heading attributes children =
    M3e.Raw.Heading.heading
        (List.map Markup.Html.Attr.toAttribute attributes)
        children


{-| Whether the heading uses an emphasized typescale. (default: `false`)
-}
emphasized : Bool -> Markup.Html.Attr.Attr { c | emphasized : M3e.Token.Supported } msg
emphasized =
    Markup.Html.Attr.Internal.attribute M3e.Raw.Heading.emphasized


{-| The accessibility level of the heading.
-}
level : Int -> Markup.Html.Attr.Attr { c | level : M3e.Token.Supported } msg
level =
    Markup.Html.Attr.Internal.attribute M3e.Raw.Heading.level


{-| The size of the heading. (default: `"medium"`)
-}
size :
    M3e.Token.Value
        { large : M3e.Token.Supported
        , medium : M3e.Token.Supported
        , small : M3e.Token.Supported
        }
    -> Markup.Html.Attr.Attr { c | size : M3e.Token.Supported } msg
size v_ =
    Markup.Html.Attr.Internal.attribute
        M3e.Raw.Heading.size
        (M3e.Token.toString v_)


{-| The appearance variant of the heading. (default: `"display"`)
-}
variant :
    M3e.Token.Value
        { display : M3e.Token.Supported
        , headline : M3e.Token.Supported
        , label : M3e.Token.Supported
        , title : M3e.Token.Supported
        }
    -> Markup.Html.Attr.Attr { c | variant : M3e.Token.Supported } msg
variant v_ =
    Markup.Html.Attr.Internal.attribute
        M3e.Raw.Heading.variant
        (M3e.Token.toString v_)


{-| Exclude this heading from the table of contents generated by an `m3e-toc` component. `m3e-toc-ignore` is a valueless presence marker the `m3e-toc` reads from heading elements; it is not an `m3e-heading` CEM attribute, so it is injected here as a heading-scoped synthetic capability.
-}
tocIgnore : Bool -> Markup.Html.Attr.Attr { c | tocIgnore : M3e.Token.Supported } msg
tocIgnore =
    Markup.Html.Attr.Internal.attribute M3e.Raw.Heading.tocIgnore
