module Sample.Motion.ShippedCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Motion.shippedCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Component.Theme as Theme
import M3e.Values
import Sample.Support exposing (appBody, model)


shown0_ =
    Theme.theme
        [ Theme.color model.seed
        , Theme.motion M3e.Values.expressive  -- spring-like emphasis (M3E's signature)
        -- , Theme.motion M3e.Values.standard   -- functional, restrained transitions
        ]
        [ appBody ]
