module Sample.Motion.SnackbarCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Motion.snackbarCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e exposing (Element)
import M3e.Unsafe
import M3e.Unsafe.Attributes
import Sample.Support exposing (Toast)
import TypedHtml.Component.Grouping


-- Elm owns WHEN the snackbar exists; the element owns the slide-in animation.
-- Render the <avt-snackbar> element (via `M3e.Unsafe.customElement`) only while
-- shown — mounting it is what triggers the toast:
snackbar : Toast -> Element (TypedHtml.Component.Grouping.DivIs s) adm_ msg
snackbar t =
    M3e.Unsafe.customElement "avt-snackbar"
        [ M3e.Unsafe.Attributes.customAttribute "message" t.message
        , M3e.Unsafe.Attributes.customAttribute "action" "Undo"
        , M3e.Unsafe.Attributes.customAttribute "dismissible" ""
        ]
        []


-- The `avt-snackbar-action` CustomEvent (detail.id) comes back through a
-- port/subscription and becomes a Msg — see Ui.Snackbar in the docs kit.
