module M3e.Review.Facts exposing (Fact, Surface(..), facts)

{-| GENERATED — per-component facts for the codegen-aware elm-review rules
(ADR 0012). Do not edit by hand; regenerate via `bin/elm-cem.js`.

@docs Fact, Surface, facts
-}


{-| The five addressable API surfaces (ADR 0013 / D6 translator spec).
`Html` = `M3e.Cem.Html.<Comp>`; `Cem` = `M3e.Cem.<Comp>`; `Standard` =
`M3e.<Comp>` (double-list top); `Record` = `M3e.Record.<Comp>` (record +
double-list); `Build` = `M3e.Build.<Comp>` (phantom-typed pipeline).
-}
type Surface
    = Html
    | Cem
    | Standard
    | Record
    | Build


{-| Per-component facts: valid enum token names per attribute, the
required/multi slot names, which surfaces the component emits at, which
HTML attributes are required (for D1 missing-required-attribute rule).
-}
type alias Fact =
    { component : String
    , module_ : String
    , enums : List ( String, List String )
    , requiredSlots : List String
    , multiSlots : List String
    , attrRewrites : List ( String, String )
    , slotRewrites : List ( String, String )
    , surfaces : List Surface
    , requiredAttrs : List String
    , actionMap : List ( String, String )
    }


{-| Every top-layer component's facts. -}
facts : List Fact
facts =
    [ { component = "tree", module_ = "M3e.Tree", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "multi", "multi" ), ( "cascade", "cascade" ), ( "onChange", "onChange" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "treeItem", module_ = "M3e.TreeItem", enums = [], requiredSlots = [ "label" ], multiSlots = [ "unnamed" ], attrRewrites = [ ( "disabled", "disabled" ), ( "indeterminate", "indeterminate" ), ( "open", "open" ), ( "selected", "selected" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "label", "label" ), ( "icon", "icon" ), ( "selected-icon", "selectedIcon" ), ( "toggle-icon", "toggleIcon" ), ( "open-toggle-icon", "openToggleIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "toolbar", module_ = "M3e.Toolbar", enums = [ ( "shape", [ "rounded", "square" ] ), ( "variant", [ "standard", "vibrant" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "elevated", "elevated" ), ( "shapeAttr", "shape" ), ( "variant", "variant" ), ( "vertical", "vertical" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "toc", module_ = "M3e.Toc", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "for", "for" ), ( "maxDepth", "maxDepth" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "overline", "overline" ), ( "title", "title" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "tocItem", module_ = "M3e.TocItem", enums = [], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "selected", "selected" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "themeIcon", module_ = "M3e.ThemeIcon", enums = [ ( "scheme", [ "auto", "dark", "light" ] ), ( "variant", [ "content", "expressive", "fidelity", "fruitSalad", "monochrome", "neutral", "rainbow", "tonalSpot", "vibrant" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "color", "color" ), ( "scheme", "scheme" ), ( "variant", "variant" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "theme", module_ = "M3e.Theme", enums = [ ( "contrast", [ "high", "medium", "standard" ] ), ( "scheme", [ "auto", "dark", "light" ] ), ( "variant", [ "content", "expressive", "fidelity", "fruitSalad", "monochrome", "neutral", "rainbow", "tonalSpot", "vibrant" ] ), ( "motion", [ "expressive", "standard" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "color", "color" ), ( "contrast", "contrast" ), ( "density", "density" ), ( "scheme", "scheme" ), ( "strongFocus", "strongFocus" ), ( "variant", "variant" ), ( "motion", "motion" ), ( "onChange", "onChange" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "textareaAutosize", module_ = "M3e.TextareaAutosize", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "maxRows", "maxRows" ), ( "minRows", "minRows" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "tabs", module_ = "M3e.Tabs", enums = [ ( "headerPosition", [ "after", "before" ] ), ( "variant", [ "primary", "secondary" ] ) ], requiredSlots = [], multiSlots = [ "unnamed", "panel" ], attrRewrites = [ ( "disablePagination", "disablePagination" ), ( "headerPosition", "headerPosition" ), ( "nextPageLabel", "nextPageLabel" ), ( "previousPageLabel", "previousPageLabel" ), ( "stretch", "stretch" ), ( "variant", "variant" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "panel", "panel" ), ( "next-icon", "nextIcon" ), ( "prev-icon", "prevIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "tabPanel", module_ = "M3e.TabPanel", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "tab", module_ = "M3e.Tab", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "selected", "selected" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "switch", module_ = "M3e.Switch", enums = [ ( "icons", [ "both", "none", "selected" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "icons", "icons" ), ( "name", "name" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "stepperReset", module_ = "M3e.StepperReset", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "stepperPrevious", module_ = "M3e.StepperPrevious", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "step", module_ = "M3e.Step", enums = [], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "completed", "completed" ), ( "disabled", "disabled" ), ( "editable", "editable" ), ( "for", "for" ), ( "optional", "optional" ), ( "selected", "selected" ), ( "invalid", "invalid" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ), ( "done-icon", "doneIcon" ), ( "edit-icon", "editIcon" ), ( "error-icon", "errorIcon" ), ( "hint", "hint" ), ( "error", "error" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "stepPanel", module_ = "M3e.StepPanel", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ), ( "actions", "actions" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "stepper", module_ = "M3e.Stepper", enums = [ ( "headerPosition", [ "above", "below" ] ), ( "labelPosition", [ "below", "end" ] ), ( "orientation", [ "auto", "horizontal", "vertical" ] ) ], requiredSlots = [], multiSlots = [ "step", "panel" ], attrRewrites = [ ( "headerPosition", "headerPosition" ), ( "labelPosition", "labelPosition" ), ( "linear", "linear" ), ( "orientation", "orientation" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ], slotRewrites = [ ( "step", "step" ), ( "panel", "panel" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "splitPane", module_ = "M3e.SplitPane", enums = [ ( "orientation", [ "auto", "horizontal", "vertical" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "label", "label" ), ( "max", "max" ), ( "min", "min" ), ( "orientation", "orientation" ), ( "overshootLimit", "overshootLimit" ), ( "stepAttr", "step" ), ( "value", "value" ), ( "wrapDetents", "wrapDetents" ), ( "name", "name" ), ( "disabled", "disabled" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ], slotRewrites = [ ( "start", "start" ), ( "end", "end" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "splitButton", module_ = "M3e.SplitButton", enums = [ ( "variant", [ "elevated", "filled", "outlined", "tonal" ] ), ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ) ], requiredSlots = [ "leading-button", "trailing-button" ], multiSlots = [], attrRewrites = [ ( "variant", "variant" ), ( "size", "size" ) ], slotRewrites = [ ( "leading-button", "leadingButton" ), ( "trailing-button", "trailingButton" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "snackbar", module_ = "M3e.Snackbar", enums = [], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "action", "action" ), ( "closeLabel", "closeLabel" ), ( "dismissible", "dismissible" ), ( "duration", "duration" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "close-icon", "closeIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "slider", module_ = "M3e.Slider", enums = [ ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [ "unnamed" ], attrRewrites = [ ( "disabled", "disabled" ), ( "discrete", "discrete" ), ( "labelled", "labelled" ), ( "max", "max" ), ( "min", "min" ), ( "stepAttr", "step" ), ( "size", "size" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "sliderThumb", module_ = "M3e.SliderThumb", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "name", "name" ), ( "value", "value" ), ( "onValueChange", "onValueChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "slideGroup", module_ = "M3e.SlideGroup", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "disabled", "disabled" ), ( "nextPageLabel", "nextPageLabel" ), ( "previousPageLabel", "previousPageLabel" ), ( "threshold", "threshold" ), ( "vertical", "vertical" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "next-icon", "nextIcon" ), ( "prev-icon", "prevIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "skeleton", module_ = "M3e.Skeleton", enums = [ ( "animation", [ "none", "pulse", "wave" ] ), ( "shape", [ "auto", "circular", "rounded", "square" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "animation", "animation" ), ( "shapeAttr", "shape" ), ( "loaded", "loaded" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "shape", module_ = "M3e.Shape", enums = [ ( "name", [ "value12SidedCookie", "value4LeafClover", "value4SidedCookie", "value6SidedCookie", "value7SidedCookie", "value8LeafClover", "value9SidedCookie", "arch", "arrow", "boom", "bun", "burst", "circle", "diamond", "fan", "flower", "gem", "ghostIsh", "heart", "hexagon", "oval", "pentagon", "pill", "pixelCircle", "pixelTriangle", "puffy", "puffyDiamond", "semicircle", "slanted", "softBoom", "softBurst", "square", "sunny", "triangle", "verySunny" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "name", "name" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "segmentedButton", module_ = "M3e.SegmentedButton", enums = [], requiredSlots = [ "unnamed" ], multiSlots = [ "unnamed" ], attrRewrites = [ ( "disabled", "disabled" ), ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "multi", "multi" ), ( "name", "name" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "buttonSegment", module_ = "M3e.ButtonSegment", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "searchView", module_ = "M3e.SearchView", enums = [ ( "mode", [ "auto", "docked", "fullscreen" ] ) ], requiredSlots = [ "input" ], multiSlots = [ "unnamed", "open-leading", "open-trailing", "closed-leading", "closed-trailing" ], attrRewrites = [ ( "contained", "contained" ), ( "mode", "mode" ), ( "open", "open" ), ( "clearLabel", "clearLabel" ), ( "closeLabel", "closeLabel" ), ( "hideSearchIcon", "hideSearchIcon" ), ( "onQuery", "onQuery" ), ( "onClear", "onClear" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "input", "input" ), ( "open-leading", "openLeading" ), ( "open-trailing", "openTrailing" ), ( "closed-leading", "closedLeading" ), ( "closed-trailing", "closedTrailing" ), ( "search-icon", "searchIcon" ), ( "close-icon", "closeIcon" ), ( "clear-icon", "clearIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "searchBar", module_ = "M3e.SearchBar", enums = [], requiredSlots = [ "input" ], multiSlots = [ "leading", "trailing" ], attrRewrites = [ ( "clearable", "clearable" ), ( "clearLabel", "clearLabel" ), ( "onClear", "onClear" ) ], slotRewrites = [ ( "leading", "leading" ), ( "input", "input" ), ( "trailing", "trailing" ), ( "clear-icon", "clearIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "radioGroup", module_ = "M3e.RadioGroup", enums = [], requiredSlots = [ "unnamed" ], multiSlots = [ "unnamed" ], attrRewrites = [ ( "ariaInvalid", "ariaInvalid" ), ( "disabled", "disabled" ), ( "name", "name" ), ( "required", "required" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "radio", module_ = "M3e.Radio", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "name", "name" ), ( "required", "required" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "progressElementIndicatorBase", module_ = "M3e.ProgressElementIndicatorBase", enums = [ ( "variant", [ "flat", "wavy" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "value", "value" ), ( "max", "max" ), ( "variant", "variant" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "paginator", module_ = "M3e.Paginator", enums = [ ( "pageSize", [ "all" ] ), ( "pageSizeVariant", [ "filled", "outlined" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "firstPageLabel", "firstPageLabel" ), ( "hidePageSize", "hidePageSize" ), ( "itemsPerPageLabel", "itemsPerPageLabel" ), ( "lastPageLabel", "lastPageLabel" ), ( "length", "length" ), ( "nextPageLabel", "nextPageLabel" ), ( "pageIndex", "pageIndex" ), ( "pageSize", "pageSize" ), ( "pageSizes", "pageSizes" ), ( "pageSizeVariant", "pageSizeVariant" ), ( "previousPageLabel", "previousPageLabel" ), ( "showFirstLastButtons", "showFirstLastButtons" ), ( "onPage", "onPage" ) ], slotRewrites = [ ( "first-page-icon", "firstPageIcon" ), ( "previous-page-icon", "previousPageIcon" ), ( "next-page-icon", "nextPageIcon" ), ( "last-page-icon", "lastPageIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "select", module_ = "M3e.Select", enums = [], requiredSlots = [ "unnamed" ], multiSlots = [ "unnamed" ], attrRewrites = [ ( "disabled", "disabled" ), ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "multi", "multi" ), ( "name", "name" ), ( "panelClass", "panelClass" ), ( "required", "required" ), ( "onChange", "onChange" ), ( "onToggle", "onToggle" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "arrow", "arrow" ), ( "value", "value" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "navRailToggle", module_ = "M3e.NavRailToggle", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "for", "for" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "navRail", module_ = "M3e.NavRail", enums = [ ( "mode", [ "auto", "compact", "expanded" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "mode", "mode" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "navMenuItemGroup", module_ = "M3e.NavMenuItemGroup", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [], slotRewrites = [ ( "label", "label" ), ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "navMenu", module_ = "M3e.NavMenu", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "navMenuItem", module_ = "M3e.NavMenuItem", enums = [], requiredSlots = [ "label" ], multiSlots = [ "unnamed" ], attrRewrites = [ ( "disabled", "disabled" ), ( "open", "open" ), ( "selected", "selected" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "label", "label" ), ( "icon", "icon" ), ( "badge", "badge" ), ( "selected-icon", "selectedIcon" ), ( "toggle-icon", "toggleIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "navBar", module_ = "M3e.NavBar", enums = [ ( "mode", [ "auto", "compact", "expanded" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "mode", "mode" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "navItem", module_ = "M3e.NavItem", enums = [ ( "orientation", [ "horizontal", "vertical" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "orientation", "orientation" ), ( "rel", "rel" ), ( "selected", "selected" ), ( "target", "target" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ), ( "selected-icon", "selectedIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "menuItemRadio", module_ = "M3e.MenuItemRadio", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "checked", "checked" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "menuItemGroup", module_ = "M3e.MenuItemGroup", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "menuItemCheckbox", module_ = "M3e.MenuItemCheckbox", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "checked", "checked" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "menu", module_ = "M3e.Menu", enums = [ ( "positionX", [ "after", "before" ] ), ( "positionY", [ "above", "below" ] ), ( "variant", [ "standard", "vibrant" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "positionX", "positionX" ), ( "positionY", "positionY" ), ( "variant", "variant" ), ( "submenu", "submenu" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "menuItem", module_ = "M3e.MenuItem", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "download", "download" ), ( "href", "href" ), ( "rel", "rel" ), ( "target", "target" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "menuTrigger", module_ = "M3e.MenuTrigger", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "for", "for" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "menuItemElementBase", module_ = "M3e.MenuItemElementBase", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "onClick", "onClick" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "loadingIndicator", module_ = "M3e.LoadingIndicator", enums = [ ( "variant", [ "contained", "uncontained" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "variant", "variant" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "selectionList", module_ = "M3e.SelectionList", enums = [ ( "variant", [ "segmented", "standard" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "multi", "multi" ), ( "variant", "variant" ), ( "name", "name" ), ( "disabled", "disabled" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "listOption", module_ = "M3e.ListOption", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "selected", "selected" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "trailing", "trailing" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "actionList", module_ = "M3e.ActionList", enums = [ ( "variant", [ "segmented", "standard" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "variant", "variant" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "expandableListItem", module_ = "M3e.ExpandableListItem", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "open", "open" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "toggle-icon", "toggleIcon" ), ( "items", "items" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "listAction", module_ = "M3e.ListAction", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "download", "download" ), ( "href", "href" ), ( "rel", "rel" ), ( "target", "target" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "trailing", "trailing" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "listItemButton", module_ = "M3e.ListItemButton", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "href", "href" ), ( "target", "target" ), ( "rel", "rel" ), ( "download", "download" ), ( "disabled", "disabled" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "trailing", "trailing" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "list", module_ = "M3e.List", enums = [ ( "variant", [ "segmented", "standard" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "variant", "variant" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "listItem", module_ = "M3e.ListItem", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ), ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "trailing", "trailing" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "icon", module_ = "M3e.Icon", enums = [ ( "grade", [ "high", "low", "medium" ] ), ( "variant", [ "outlined", "rounded", "sharp" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "filled", "filled" ), ( "grade", "grade" ), ( "opticalSize", "opticalSize" ), ( "name", "name" ), ( "variant", "variant" ), ( "weight", "weight" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "heading", module_ = "M3e.Heading", enums = [ ( "size", [ "large", "medium", "small" ] ), ( "variant", [ "display", "headline", "label", "title" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "emphasized", "emphasized" ), ( "level", "level" ), ( "size", "size" ), ( "variant", "variant" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "fabMenuTrigger", module_ = "M3e.FabMenuTrigger", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "for", "for" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "fabMenu", module_ = "M3e.FabMenu", enums = [ ( "variant", [ "primary", "secondary", "tertiary" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "variant", "variant" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "fab", module_ = "M3e.Fab", enums = [ ( "size", [ "large", "medium", "small" ] ), ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "primary", "primaryContainer", "secondary", "secondaryContainer", "surface", "tertiary", "tertiaryContainer" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "extended", "extended" ), ( "href", "href" ), ( "lowered", "lowered" ), ( "name", "name" ), ( "rel", "rel" ), ( "size", "size" ), ( "target", "target" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "label", "label" ), ( "close-icon", "closeIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [ "aria-label" ], actionMap = [] }
    , { component = "accordion", module_ = "M3e.Accordion", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "multi", "multi" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "expansionPanel", module_ = "M3e.ExpansionPanel", enums = [ ( "toggleDirection", [ "horizontal", "vertical" ] ), ( "togglePosition", [ "after", "before" ] ) ], requiredSlots = [], multiSlots = [ "actions" ], attrRewrites = [ ( "disabled", "disabled" ), ( "hideToggle", "hideToggle" ), ( "open", "open" ), ( "toggleDirection", "toggleDirection" ), ( "togglePosition", "togglePosition" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "actions", "actions" ), ( "header", "header" ), ( "toggle-icon", "toggleIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "expansionHeader", module_ = "M3e.ExpansionHeader", enums = [ ( "toggleDirection", [ "horizontal", "vertical" ] ), ( "togglePosition", [ "after", "before" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "hideToggle", "hideToggle" ), ( "toggleDirection", "toggleDirection" ), ( "togglePosition", "togglePosition" ), ( "disabled", "disabled" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "toggle-icon", "toggleIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "drawerToggle", module_ = "M3e.DrawerToggle", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "for", "for" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "drawerContainer", module_ = "M3e.DrawerContainer", enums = [ ( "endMode", [ "auto", "over", "push", "side" ] ), ( "startMode", [ "auto", "over", "push", "side" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "end", "end" ), ( "endMode", "endMode" ), ( "endDivider", "endDivider" ), ( "start", "start" ), ( "startMode", "startMode" ), ( "startDivider", "startDivider" ), ( "onChange", "onChange" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "start", "startSlot" ), ( "end", "endSlot" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "divider", module_ = "M3e.Divider", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "inset", "inset" ), ( "insetStart", "insetStart" ), ( "insetEnd", "insetEnd" ), ( "vertical", "vertical" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "dialogTrigger", module_ = "M3e.DialogTrigger", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "for", "for" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "dialog", module_ = "M3e.Dialog", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "alert", "alert" ), ( "closeLabel", "closeLabel" ), ( "disableClose", "disableClose" ), ( "dismissible", "dismissible" ), ( "noFocusTrap", "noFocusTrap" ), ( "open", "open" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ), ( "onCancel", "onCancel" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "header", "header" ), ( "actions", "actions" ), ( "close-icon", "closeIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "dialogAction", module_ = "M3e.DialogAction", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "returnValue", "returnValue" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "datepickerToggle", module_ = "M3e.DatepickerToggle", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "for", "for" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "datepicker", module_ = "M3e.Datepicker", enums = [ ( "variant", [ "auto", "docked", "modal" ] ), ( "startView", [ "month", "multiYear", "year" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "variant", "variant" ), ( "clearable", "clearable" ), ( "date", "date" ), ( "maxDate", "maxDate" ), ( "minDate", "minDate" ), ( "range", "range" ), ( "rangeEnd", "rangeEnd" ), ( "rangeStart", "rangeStart" ), ( "startAt", "startAt" ), ( "startView", "startView" ), ( "previousMonthLabel", "previousMonthLabel" ), ( "nextMonthLabel", "nextMonthLabel" ), ( "previousYearLabel", "previousYearLabel" ), ( "nextYearLabel", "nextYearLabel" ), ( "previousMultiYearLabel", "previousMultiYearLabel" ), ( "nextMultiYearLabel", "nextMultiYearLabel" ), ( "clearLabel", "clearLabel" ), ( "confirmLabel", "confirmLabel" ), ( "dismissLabel", "dismissLabel" ), ( "label", "label" ), ( "onChange", "onChange" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "contentPane", module_ = "M3e.ContentPane", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "suggestionChip", module_ = "M3e.SuggestionChip", enums = [ ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "elevated", "outlined" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "name", "name" ), ( "rel", "rel" ), ( "target", "target" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "inputChipSet", module_ = "M3e.InputChipSet", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "disabled", "disabled" ), ( "name", "name" ), ( "required", "required" ), ( "vertical", "vertical" ), ( "onChange", "onChange" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "input", "input" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "inputChip", module_ = "M3e.InputChip", enums = [ ( "variant", [ "elevated", "outlined" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "removable", "removable" ), ( "removeLabel", "removeLabel" ), ( "value", "value" ), ( "variant", "variant" ), ( "onRemove", "onRemove" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "avatar", "avatar" ), ( "icon", "icon" ), ( "remove-icon", "removeIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "filterChipSet", module_ = "M3e.FilterChipSet", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "disabled", "disabled" ), ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "multi", "multi" ), ( "name", "name" ), ( "vertical", "vertical" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "filterChip", module_ = "M3e.FilterChip", enums = [ ( "variant", [ "elevated", "outlined" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "selected", "selected" ), ( "value", "value" ), ( "variant", "variant" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "chipSet", module_ = "M3e.ChipSet", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "vertical", "vertical" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "assistChip", module_ = "M3e.AssistChip", enums = [ ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "elevated", "outlined" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "name", "name" ), ( "rel", "rel" ), ( "target", "target" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "chip", module_ = "M3e.Chip", enums = [ ( "variant", [ "elevated", "outlined" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "value", "value" ), ( "variant", "variant" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "checkbox", module_ = "M3e.Checkbox", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "indeterminate", "indeterminate" ), ( "name", "name" ), ( "required", "required" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onInvalid", "onInvalid" ), ( "onClick", "onClick" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "card", module_ = "M3e.Card", enums = [ ( "orientation", [ "horizontal", "vertical" ] ), ( "variant", [ "elevated", "filled", "outlined" ] ), ( "type_", [ "button", "reset", "submit" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "actionable", "actionable" ), ( "inline", "inline" ), ( "orientation", "orientation" ), ( "variant", "variant" ), ( "href", "href" ), ( "target", "target" ), ( "rel", "rel" ), ( "download", "download" ), ( "name", "name" ), ( "value", "value" ), ( "type_", "type_" ), ( "disabledInteractive", "disabledInteractive" ), ( "disabled", "disabled" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "header", "header" ), ( "content", "content" ), ( "actions", "actions" ), ( "footer", "footer" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "calendar", module_ = "M3e.Calendar", enums = [ ( "startView", [ "month", "multiYear", "year" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "date", "date" ), ( "maxDate", "maxDate" ), ( "minDate", "minDate" ), ( "rangeEnd", "rangeEnd" ), ( "rangeStart", "rangeStart" ), ( "startAt", "startAt" ), ( "startView", "startView" ), ( "previousMonthLabel", "previousMonthLabel" ), ( "nextMonthLabel", "nextMonthLabel" ), ( "previousYearLabel", "previousYearLabel" ), ( "nextYearLabel", "nextYearLabel" ), ( "previousMultiYearLabel", "previousMultiYearLabel" ), ( "nextMultiYearLabel", "nextMultiYearLabel" ), ( "onChange", "onChange" ) ], slotRewrites = [ ( "header", "header" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "yearView", module_ = "M3e.YearView", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "active", "active" ), ( "today", "today" ), ( "date", "date" ), ( "activeDate", "activeDate" ), ( "minDate", "minDate" ), ( "maxDate", "maxDate" ), ( "onChange", "onChange" ), ( "onActiveChange", "onActiveChange" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "multiYearView", module_ = "M3e.MultiYearView", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "active", "active" ), ( "today", "today" ), ( "date", "date" ), ( "activeDate", "activeDate" ), ( "minDate", "minDate" ), ( "maxDate", "maxDate" ), ( "onChange", "onChange" ), ( "onActiveChange", "onActiveChange" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "monthView", module_ = "M3e.MonthView", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "rangeStart", "rangeStart" ), ( "rangeEnd", "rangeEnd" ), ( "active", "active" ), ( "today", "today" ), ( "date", "date" ), ( "activeDate", "activeDate" ), ( "minDate", "minDate" ), ( "maxDate", "maxDate" ), ( "onChange", "onChange" ), ( "onActiveChange", "onActiveChange" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "tooltip", module_ = "M3e.Tooltip", enums = [ ( "position", [ "above", "after", "before", "below" ] ), ( "touchGestures", [ "auto", "off", "on" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "hideDelay", "hideDelay" ), ( "position", "position" ), ( "showDelay", "showDelay" ), ( "touchGestures", "touchGestures" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "richTooltip", module_ = "M3e.RichTooltip", enums = [ ( "position", [ "above", "aboveAfter", "aboveBefore", "after", "before", "below", "belowAfter", "belowBefore" ] ), ( "touchGestures", [ "auto", "off", "on" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "hideDelay", "hideDelay" ), ( "position", "position" ), ( "showDelay", "showDelay" ), ( "touchGestures", "touchGestures" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "subhead", "subhead" ), ( "actions", "actions" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "tooltipElementBase", module_ = "M3e.TooltipElementBase", enums = [ ( "touchGestures", [ "auto", "off", "on" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "showDelay", "showDelay" ), ( "hideDelay", "hideDelay" ), ( "touchGestures", "touchGestures" ), ( "for", "for" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "richTooltipAction", module_ = "M3e.RichTooltipAction", enums = [], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disableRestoreFocus", "disableRestoreFocus" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "buttonGroup", module_ = "M3e.ButtonGroup", enums = [ ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ), ( "variant", [ "connected", "standard" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "multi", "multi" ), ( "size", "size" ), ( "variant", "variant" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "iconButton", module_ = "M3e.IconButton", enums = [ ( "shape", [ "rounded", "square" ] ), ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ), ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "filled", "outlined", "standard", "tonal" ] ), ( "width", [ "default", "narrow", "wide" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "name", "name" ), ( "rel", "rel" ), ( "selected", "selected" ), ( "shapeAttr", "shape" ), ( "size", "size" ), ( "target", "target" ), ( "toggle", "toggle" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "width", "width" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "selected", "selectedSlot" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [ "aria-label" ], actionMap = [] }
    , { component = "button", module_ = "M3e.Button", enums = [ ( "shape", [ "rounded", "square" ] ), ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ), ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "elevated", "filled", "outlined", "text", "tonal" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "name", "name" ), ( "rel", "rel" ), ( "selected", "selected" ), ( "shapeAttr", "shape" ), ( "size", "size" ), ( "target", "target" ), ( "toggle", "toggle" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ), ( "selected", "selectedSlot" ), ( "selected-icon", "selectedIcon" ), ( "trailing-icon", "trailingIcon" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ] }
    , { component = "breadcrumb", module_ = "M3e.Breadcrumb", enums = [], requiredSlots = [ "unnamed" ], multiSlots = [ "unnamed" ], attrRewrites = [ ( "wrap", "wrap" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "separator", "separator" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "breadcrumbItem", module_ = "M3e.BreadcrumbItem", enums = [ ( "current", [ "date", "location", "page", "step", "time", "true" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "itemLabel", "itemLabel" ), ( "disabled", "disabled" ), ( "current", "current" ), ( "href", "href" ), ( "target", "target" ), ( "download", "download" ), ( "rel", "rel" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "icon", "icon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "breadcrumbItemButton", module_ = "M3e.BreadcrumbItemButton", enums = [ ( "current", [ "date", "location", "page", "step", "time", "true" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "current", "current" ), ( "href", "href" ), ( "target", "target" ), ( "rel", "rel" ), ( "download", "download" ), ( "disabled", "disabled" ), ( "onClick", "onClick" ) ], slotRewrites = [ ( "icon", "icon" ), ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "bottomSheetTrigger", module_ = "M3e.BottomSheetTrigger", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "detent", "detent" ), ( "secondary", "secondary" ), ( "for", "for" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "bottomSheet", module_ = "M3e.BottomSheet", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "detent", "detent" ), ( "handle", "handle" ), ( "handleLabel", "handleLabel" ), ( "hideable", "hideable" ), ( "hideFriction", "hideFriction" ), ( "modal", "modal" ), ( "open", "open" ), ( "overshootLimit", "overshootLimit" ), ( "onOpening", "onOpening" ), ( "onClosing", "onClosing" ), ( "onCancel", "onCancel" ), ( "onOpened", "onOpened" ), ( "onClosed", "onClosed" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "header", "header" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "bottomSheetAction", module_ = "M3e.BottomSheetAction", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "badge", module_ = "M3e.Badge", enums = [ ( "size", [ "large", "medium", "small" ] ), ( "position", [ "above", "aboveAfter", "aboveBefore", "after", "before", "below", "belowAfter", "belowBefore" ] ) ], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "size", "size" ), ( "position", "position" ), ( "for", "for" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "avatar", module_ = "M3e.Avatar", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "autocomplete", module_ = "M3e.Autocomplete", enums = [ ( "filter", [ "contains", "endsWith", "none", "startsWith" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "autoActivate", "autoActivate" ), ( "caseSensitive", "caseSensitive" ), ( "filter", "filter" ), ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "hideLoading", "hideLoading" ), ( "hideNoData", "hideNoData" ), ( "loading", "loading" ), ( "loadingLabel", "loadingLabel" ), ( "noDataLabel", "noDataLabel" ), ( "panelClass", "panelClass" ), ( "required", "required" ), ( "for", "for" ), ( "onChange", "onChange" ), ( "onQuery", "onQuery" ), ( "onToggle", "onToggle" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "loading", "loadingSlot" ), ( "no-data", "noData" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "formField", module_ = "M3e.FormField", enums = [ ( "floatLabel", [ "always", "auto" ] ), ( "hideSubscript", [ "always", "auto", "never" ] ), ( "variant", [ "filled", "outlined" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "floatLabel", "floatLabel" ), ( "hideRequiredMarker", "hideRequiredMarker" ), ( "hideSubscript", "hideSubscript" ), ( "variant", "variant" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "prefix", "prefix" ), ( "prefix-text", "prefixText" ), ( "label", "label" ), ( "suffix", "suffix" ), ( "suffix-text", "suffixText" ), ( "hint", "hint" ), ( "error", "error" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "optionPanel", module_ = "M3e.OptionPanel", enums = [ ( "state", [ "content", "loading", "noData" ] ), ( "scrollStrategy", [ "hide", "reposition" ] ) ], requiredSlots = [], multiSlots = [ "unnamed", "loading" ], attrRewrites = [ ( "state", "state" ), ( "scrollStrategy", "scrollStrategy" ), ( "fitAnchorWidth", "fitAnchorWidth" ), ( "anchorOffset", "anchorOffset" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ], slotRewrites = [ ( "unnamed", "child" ), ( "no-data", "noData" ), ( "loading", "loading" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "floatingPanel", module_ = "M3e.FloatingPanel", enums = [ ( "scrollStrategy", [ "hide", "reposition" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "scrollStrategy", "scrollStrategy" ), ( "fitAnchorWidth", "fitAnchorWidth" ), ( "anchorOffset", "anchorOffset" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "optgroup", module_ = "M3e.Optgroup", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ), ( "label", "label" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "option", module_ = "M3e.Option", enums = [ ( "highlightMode", [ "contains", "endsWith", "startsWith" ] ) ], requiredSlots = [ "unnamed" ], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disableHighlight", "disableHighlight" ), ( "highlightMode", "highlightMode" ), ( "selected", "selected" ), ( "term", "term" ), ( "value", "value" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Record, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "focusTrap", module_ = "M3e.FocusTrap", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "disabled", "disabled" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "appBar", module_ = "M3e.AppBar", enums = [ ( "size", [ "large", "medium", "small" ] ) ], requiredSlots = [], multiSlots = [ "trailing" ], attrRewrites = [ ( "centered", "centered" ), ( "for", "for" ), ( "size", "size" ) ], slotRewrites = [ ( "leading", "leading" ), ( "title", "title" ), ( "subtitle", "subtitle" ), ( "trailing", "trailing" ), ( "leading-icon", "leadingIcon" ), ( "trailing-icon", "trailingIcon" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "textOverflow", module_ = "M3e.TextOverflow", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "textHighlight", module_ = "M3e.TextHighlight", enums = [ ( "mode", [ "contains", "endsWith", "startsWith" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "caseSensitive", "caseSensitive" ), ( "disabled", "disabled" ), ( "mode", "mode" ), ( "term", "term" ), ( "onHighlight", "onHighlight" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "stateLayer", module_ = "M3e.StateLayer", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "disableHover", "disableHover" ), ( "for", "for" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "slide", module_ = "M3e.Slide", enums = [], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "selectedIndex", "selectedIndex" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "scrollContainer", module_ = "M3e.ScrollContainer", enums = [ ( "dividers", [ "above", "aboveBelow", "below", "none" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "dividers", "dividers" ), ( "thin", "thin" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "ripple", module_ = "M3e.Ripple", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "centered", "centered" ), ( "disabled", "disabled" ), ( "for", "for" ), ( "radius", "radius" ), ( "unbounded", "unbounded" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "pseudoRadio", module_ = "M3e.PseudoRadio", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "pseudoCheckbox", module_ = "M3e.PseudoCheckbox", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "indeterminate", "indeterminate" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "focusRing", module_ = "M3e.FocusRing", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "inward", "inward" ), ( "for", "for" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "elevation", module_ = "M3e.Elevation", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "level", "level" ) ], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "collapsible", module_ = "M3e.Collapsible", enums = [ ( "orientation", [ "horizontal", "vertical" ] ) ], requiredSlots = [], multiSlots = [ "unnamed" ], attrRewrites = [ ( "open", "open" ), ( "orientation", "orientation" ), ( "noAnimate", "noAnimate" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ) ], slotRewrites = [ ( "unnamed", "child" ) ], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    , { component = "actionElementBase", module_ = "M3e.ActionElementBase", enums = [], requiredSlots = [], multiSlots = [], attrRewrites = [], slotRewrites = [], surfaces = [ Html, Cem, Standard, Build ], requiredAttrs = [], actionMap = [] }
    ]
