module Sample.Strictness.ShapesCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Strictness.shapesCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Action
import M3e.Attributes
import M3e.Build
import M3e.Build.Button
import M3e.Component.Button
import M3e.Values as Value
import Sample.Support exposing (Msg(..))


-- the standard form — everything optional; the tersest, easiest form
shown0_ =
    M3e.button [ M3e.Attributes.variant Value.filled ] [ M3e.text "Save" ]


-- required-record form (`component`) — the compiler now DEMANDS the parts a button can't do without
shown1_ =
    M3e.Component.Button.component
        { content = M3e.text "Save", action = M3e.Action.onClick SaveClicked }
        []
        []


-- builder pipe (`build`/`toElement`) — a one-only setter becomes UNWRITABLE twice; order-free
shown2_ =
    M3e.Build.Button.build
        { content = M3e.text "Save", action = M3e.Action.onClick SaveClicked }
        |> M3e.Build.Button.toElement
