module M3e.Review.Facts exposing (facts, reExposedValueTokens)

{-| GENERATED review facts for the elm-review-cem rules (phantom pipeline).

@docs facts, reExposedValueTokens

-}

import Cem.Facts exposing (Facet(..), Fact)


{-| Per-component facts.
-}
facts : List Fact
facts =
    [ { component = "accordion"
      , module_ = "M3e.Accordion"
      , enums = []
      , requiredSlots = [ "unnamed" ]
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "multi", "multi" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "expansionPanel" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "actionList"
      , module_ = "M3e.ActionList"
      , enums = [ ( "variant", [ "segmented", "standard" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "variant", "variant" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "divider", "expandableListItem", "listAction" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "appBar"
      , module_ = "M3e.AppBar"
      , enums = [ ( "size", [ "large", "medium", "small" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "trailing" ]
      , attrRewrites = [ ( "centered", "centered" ), ( "for", "for" ), ( "size", "size" ) ]
      , slotRewrites = [ ( "leading", "leading" ), ( "leading-icon", "leadingIcon" ), ( "subtitle", "subtitle" ), ( "title", "title" ), ( "trailing", "trailing" ), ( "trailing-icon", "trailingIcon" ) ]
      , slotKinds = [ ( "leading", [ "button", "iconButton", "shared:icon" ] ), ( "subtitle", [ "html", "shared:text" ] ), ( "title", [ "html", "shared:text" ] ), ( "trailing", [ "button", "html", "iconButton", "searchBar" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "assistChip"
      , module_ = "M3e.AssistChip"
      , enums = [ ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "elevated", "outlined" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "name", "name" ), ( "rel", "rel" ), ( "target", "target" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = False
      }
    , { component = "autocomplete"
      , module_ = "M3e.Autocomplete"
      , enums = [ ( "filter", [ "contains", "endsWith", "none", "startsWith" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "autoActivate", "autoActivate" ), ( "caseSensitive", "caseSensitive" ), ( "filter", "filter" ), ( "for", "for" ), ( "hideLoading", "hideLoading" ), ( "hideNoData", "hideNoData" ), ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "loading", "loading" ), ( "loadingLabel", "loadingLabel" ), ( "noDataLabel", "noDataLabel" ), ( "panelClass", "panelClass" ), ( "required", "required" ), ( "resultsLabel", "resultsLabel" ), ( "onChange", "onChange" ), ( "onQuery", "onQuery" ), ( "onToggle", "onToggle" ) ]
      , slotRewrites = [ ( "loading", "loading" ), ( "no-data", "noData" ) ]
      , slotKinds = [ ( "unnamed", [ "optgroup", "option" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "avatar"
      , module_ = "M3e.Avatar"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "badge"
      , module_ = "M3e.Badge"
      , enums = [ ( "position", [ "above", "aboveAfter", "aboveBefore", "after", "before", "below", "belowAfter", "belowBefore" ] ), ( "size", [ "large", "medium", "small" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "for", "for" ), ( "position", "position" ), ( "size", "size" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "bottomSheet"
      , module_ = "M3e.BottomSheet"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "detent", "detent" ), ( "detents", "detents" ), ( "handle", "handle" ), ( "handleLabel", "handleLabel" ), ( "hideFriction", "hideFriction" ), ( "hideable", "hideable" ), ( "modal", "modal" ), ( "open", "open" ), ( "overshootLimit", "overshootLimit" ), ( "onOpening", "onOpening" ), ( "onClosing", "onClosing" ), ( "onCancel", "onCancel" ), ( "onOpened", "onOpened" ), ( "onClosed", "onClosed" ) ]
      , slotRewrites = [ ( "header", "header" ) ]
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "bottomSheetAction"
      , module_ = "M3e.BottomSheetAction"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "bottomSheetTrigger"
      , module_ = "M3e.BottomSheetTrigger"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "detent", "detent" ), ( "for", "for" ), ( "secondary", "secondary" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "breadcrumb"
      , module_ = "M3e.Breadcrumb"
      , enums = []
      , requiredSlots = [ "unnamed" ]
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "wrap", "wrap" ) ]
      , slotRewrites = [ ( "separator", "separator" ) ]
      , slotKinds = [ ( "unnamed", [ "breadcrumbItem" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "breadcrumbItem"
      , module_ = "M3e.BreadcrumbItem"
      , enums = [ ( "current", [ "date", "location", "page", "step", "time", "true" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "current", "current" ), ( "disabled", "disabled" ), ( "download", "download" ), ( "href", "href" ), ( "itemLabel", "itemLabel" ), ( "rel", "rel" ), ( "target", "target" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:icon", "shared:text" ] ), ( "icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = False
      }
    , { component = "breadcrumbItemButton"
      , module_ = "M3e.BreadcrumbItemButton"
      , enums = [ ( "current", [ "date", "location", "page", "step", "time", "true" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "current", "current" ), ( "disabled", "disabled" ), ( "download", "download" ), ( "href", "href" ), ( "rel", "rel" ), ( "target", "target" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:icon", "shared:text" ] ), ( "icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = False
      }
    , { component = "button"
      , module_ = "M3e.Button"
      , enums = [ ( "shape", [ "rounded", "square" ] ), ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ), ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "elevated", "filled", "outlined", "text", "tonal" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "name", "name" ), ( "rel", "rel" ), ( "selected", "selected" ), ( "shape", "shape" ), ( "size", "size" ), ( "target", "target" ), ( "toggle", "toggle" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ), ( "selected", "selected" ), ( "selected-icon", "selectedIcon" ), ( "trailing-icon", "trailingIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "bottomSheetAction", "bottomSheetTrigger", "datepickerToggle", "dialogAction", "dialogTrigger", "drawerToggle", "fabMenuTrigger", "menuTrigger", "navRailToggle", "richTooltipAction", "shared:icon", "shared:text", "stepperNext", "stepperPrevious", "stepperReset" ] ), ( "icon", [ "loadingIndicator", "shared:icon" ] ), ( "selected", [ "shared:icon", "shared:text" ] ), ( "selected-icon", [ "shared:icon" ] ), ( "trailing-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = True
      }
    , { component = "buttonGroup"
      , module_ = "M3e.ButtonGroup"
      , enums = [ ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ), ( "variant", [ "connected", "standard" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "multi", "multi" ), ( "size", "size" ), ( "variant", "variant" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "button", "iconButton" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "buttonSegment"
      , module_ = "M3e.ButtonSegment"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "calendar"
      , module_ = "M3e.Calendar"
      , enums = [ ( "startView", [ "month", "multiYear", "year" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "date", "date" ), ( "maxDate", "maxDate" ), ( "minDate", "minDate" ), ( "nextMonthLabel", "nextMonthLabel" ), ( "nextMultiYearLabel", "nextMultiYearLabel" ), ( "nextYearLabel", "nextYearLabel" ), ( "previousMonthLabel", "previousMonthLabel" ), ( "previousMultiYearLabel", "previousMultiYearLabel" ), ( "previousYearLabel", "previousYearLabel" ), ( "rangeEnd", "rangeEnd" ), ( "rangeStart", "rangeStart" ), ( "startAt", "startAt" ), ( "startView", "startView" ), ( "onChange", "onChange" ) ]
      , slotRewrites = [ ( "header", "header" ) ]
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "card"
      , module_ = "M3e.Card"
      , enums = [ ( "orientation", [ "horizontal", "vertical" ] ), ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "elevated", "filled", "outlined" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "actionable", "actionable" ), ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "inline", "inline" ), ( "name", "name" ), ( "orientation", "orientation" ), ( "rel", "rel" ), ( "target", "target" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "actions", "actions" ), ( "content", "content" ), ( "footer", "footer" ), ( "header", "header" ) ]
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = False
      }
    , { component = "checkbox"
      , module_ = "M3e.Checkbox"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "indeterminate", "indeterminate" ), ( "name", "name" ), ( "required", "required" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onInvalid", "onInvalid" ), ( "onClick", "onClick" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "chip"
      , module_ = "M3e.Chip"
      , enums = [ ( "variant", [ "elevated", "outlined" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "value", "value" ), ( "variant", "variant" ) ]
      , slotRewrites = [ ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ), ( "trailing-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "chipSet"
      , module_ = "M3e.ChipSet"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "vertical", "vertical" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "assistChip", "chip", "filterChip", "inputChip", "suggestionChip" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "circularProgressIndicator"
      , module_ = "M3e.CircularProgressIndicator"
      , enums = [ ( "variant", [ "flat", "wavy" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "indeterminate", "indeterminate" ), ( "max", "max" ), ( "value", "value" ), ( "variant", "variant" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "collapsible"
      , module_ = "M3e.Collapsible"
      , enums = [ ( "orientation", [ "horizontal", "vertical" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "noAnimate", "noAnimate" ), ( "open", "open" ), ( "orientation", "orientation" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "contentPane"
      , module_ = "M3e.ContentPane"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "datepicker"
      , module_ = "M3e.Datepicker"
      , enums = [ ( "startView", [ "month", "multiYear", "year" ] ), ( "variant", [ "auto", "docked", "modal" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "clearLabel", "clearLabel" ), ( "clearable", "clearable" ), ( "confirmLabel", "confirmLabel" ), ( "date", "date" ), ( "dismissLabel", "dismissLabel" ), ( "label", "label" ), ( "maxDate", "maxDate" ), ( "minDate", "minDate" ), ( "nextMonthLabel", "nextMonthLabel" ), ( "nextMultiYearLabel", "nextMultiYearLabel" ), ( "nextYearLabel", "nextYearLabel" ), ( "previousMonthLabel", "previousMonthLabel" ), ( "previousMultiYearLabel", "previousMultiYearLabel" ), ( "previousYearLabel", "previousYearLabel" ), ( "range", "range" ), ( "rangeEnd", "rangeEnd" ), ( "rangeStart", "rangeStart" ), ( "startAt", "startAt" ), ( "startView", "startView" ), ( "variant", "variant" ), ( "onChange", "onChange" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "datepickerToggle"
      , module_ = "M3e.DatepickerToggle"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "for", "for" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "dialog"
      , module_ = "M3e.Dialog"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "alert", "alert" ), ( "closeLabel", "closeLabel" ), ( "disableClose", "disableClose" ), ( "dismissible", "dismissible" ), ( "noFocusTrap", "noFocusTrap" ), ( "open", "open" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ), ( "onCancel", "onCancel" ) ]
      , slotRewrites = [ ( "actions", "actions" ), ( "close-icon", "closeIcon" ), ( "header", "header" ) ]
      , slotKinds = [ ( "close-icon", [ "shared:icon" ] ), ( "header", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "dialogAction"
      , module_ = "M3e.DialogAction"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "returnValue", "returnValue" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "dialogTrigger"
      , module_ = "M3e.DialogTrigger"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "for", "for" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "divider"
      , module_ = "M3e.Divider"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "inset", "inset" ), ( "insetEnd", "insetEnd" ), ( "insetStart", "insetStart" ), ( "vertical", "vertical" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "drawerContainer"
      , module_ = "M3e.DrawerContainer"
      , enums = [ ( "endMode", [ "auto", "over", "push", "side" ] ), ( "startMode", [ "auto", "over", "push", "side" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "end", "end" ), ( "endDivider", "endDivider" ), ( "endMode", "endMode" ), ( "start", "start" ), ( "startDivider", "startDivider" ), ( "startMode", "startMode" ), ( "onChange", "onChange" ) ]
      , slotRewrites = [ ( "end", "end" ), ( "start", "start" ) ]
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "drawerToggle"
      , module_ = "M3e.DrawerToggle"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "for", "for" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "elevation"
      , module_ = "M3e.Elevation"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "level", "level" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "expandableListItem"
      , module_ = "M3e.ExpandableListItem"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "open", "open" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ) ]
      , slotRewrites = [ ( "items", "items" ), ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "toggle-icon", "toggleIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "html", "shared:text" ] ), ( "leading", [ "avatar", "html", "shared:icon", "shared:text" ] ), ( "overline", [ "html", "shared:text" ] ), ( "supporting-text", [ "html", "shared:text" ] ), ( "toggle-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "expansionHeader"
      , module_ = "M3e.ExpansionHeader"
      , enums = [ ( "toggleDirection", [ "horizontal", "vertical" ] ), ( "togglePosition", [ "after", "before" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "hideToggle", "hideToggle" ), ( "toggleDirection", "toggleDirection" ), ( "togglePosition", "togglePosition" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "toggle-icon", "toggleIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "toggle-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "expansionPanel"
      , module_ = "M3e.ExpansionPanel"
      , enums = [ ( "toggleDirection", [ "horizontal", "vertical" ] ), ( "togglePosition", [ "after", "before" ] ) ]
      , requiredSlots = [ "header" ]
      , multiSlots = [ "actions" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "hideToggle", "hideToggle" ), ( "open", "open" ), ( "toggleDirection", "toggleDirection" ), ( "togglePosition", "togglePosition" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ) ]
      , slotRewrites = [ ( "actions", "actions" ), ( "header", "header" ), ( "toggle-icon", "toggleIcon" ) ]
      , slotKinds = [ ( "toggle-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "fab"
      , module_ = "M3e.Fab"
      , enums = [ ( "size", [ "large", "medium", "small" ] ), ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "primary", "primaryContainer", "secondary", "secondaryContainer", "surface", "tertiary", "tertiaryContainer" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "extended", "extended" ), ( "href", "href" ), ( "lowered", "lowered" ), ( "name", "name" ), ( "rel", "rel" ), ( "size", "size" ), ( "target", "target" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "close-icon", "closeIcon" ), ( "label", "label" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:icon" ] ), ( "close-icon", [ "shared:icon" ] ), ( "label", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = [ "aria-label" ]
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = True
      }
    , { component = "fabMenu"
      , module_ = "M3e.FabMenu"
      , enums = [ ( "variant", [ "primary", "secondary", "tertiary" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "variant", "variant" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "fabMenuItem", "menuItem" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "fabMenuItem"
      , module_ = "M3e.FabMenuItem"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "download", "download" ), ( "href", "href" ), ( "rel", "rel" ), ( "target", "target" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ) ]
      , slotKinds = [ ( "icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "fabMenuTrigger"
      , module_ = "M3e.FabMenuTrigger"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "for", "for" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "filterChip"
      , module_ = "M3e.FilterChip"
      , enums = [ ( "variant", [ "elevated", "outlined" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "selected", "selected" ), ( "value", "value" ), ( "variant", "variant" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ), ( "trailing-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "filterChipSet"
      , module_ = "M3e.FilterChipSet"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "multi", "multi" ), ( "name", "name" ), ( "vertical", "vertical" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "filterChip" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "floatingPanel"
      , module_ = "M3e.FloatingPanel"
      , enums = [ ( "scrollStrategy", [ "hide", "reposition" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "anchorOffset", "anchorOffset" ), ( "fitAnchorWidth", "fitAnchorWidth" ), ( "scrollStrategy", "scrollStrategy" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "focusRing"
      , module_ = "M3e.FocusRing"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "inward", "inward" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "focusTrap"
      , module_ = "M3e.FocusTrap"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "formField"
      , module_ = "M3e.FormField"
      , enums = [ ( "floatLabel", [ "always", "auto" ] ), ( "hideSubscript", [ "always", "auto", "never" ] ), ( "variant", [ "filled", "outlined" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "floatLabel", "floatLabel" ), ( "hideRequiredMarker", "hideRequiredMarker" ), ( "hideSubscript", "hideSubscript" ), ( "variant", "variant" ) ]
      , slotRewrites = [ ( "error", "error" ), ( "hint", "hint" ), ( "prefix", "prefix" ), ( "prefix-text", "prefixText" ), ( "suffix", "suffix" ), ( "suffix-text", "suffixText" ) ]
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "heading"
      , module_ = "M3e.Heading"
      , enums = [ ( "size", [ "large", "medium", "small" ] ), ( "variant", [ "display", "headline", "label", "title" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "emphasized", "emphasized" ), ( "level", "level" ), ( "size", "size" ), ( "tocIgnore", "tocIgnore" ), ( "variant", "variant" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "icon"
      , module_ = "M3e.Icon"
      , enums = [ ( "grade", [ "high", "low", "medium" ] ), ( "variant", [ "outlined", "rounded", "sharp" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "filled", "filled" ), ( "grade", "grade" ), ( "name", "name" ), ( "opticalSize", "opticalSize" ), ( "variant", "variant" ), ( "weight", "weight" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "iconButton"
      , module_ = "M3e.IconButton"
      , enums = [ ( "shape", [ "rounded", "square" ] ), ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ), ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "filled", "outlined", "standard", "tonal" ] ), ( "width", [ "default", "narrow", "wide" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "name", "name" ), ( "rel", "rel" ), ( "selected", "selected" ), ( "shape", "shape" ), ( "size", "size" ), ( "target", "target" ), ( "toggle", "toggle" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "width", "width" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "selected", "selected" ) ]
      , slotKinds = [ ( "unnamed", [ "bottomSheetAction", "bottomSheetTrigger", "datepickerToggle", "dialogAction", "dialogTrigger", "drawerToggle", "fabMenuTrigger", "menuTrigger", "navRailToggle", "richTooltipAction", "shared:icon", "stepperNext", "stepperPrevious", "stepperReset" ] ), ( "selected", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = [ "aria-label" ]
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = True
      }
    , { component = "inputChip"
      , module_ = "M3e.InputChip"
      , enums = [ ( "variant", [ "elevated", "outlined" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "removable", "removable" ), ( "removeLabel", "removeLabel" ), ( "value", "value" ), ( "variant", "variant" ), ( "onRemove", "onRemove" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "avatar", "avatar" ), ( "icon", "icon" ), ( "remove-icon", "removeIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "avatar", [ "avatar" ] ), ( "icon", [ "shared:icon" ] ), ( "remove-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "inputChipSet"
      , module_ = "M3e.InputChipSet"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "name", "name" ), ( "required", "required" ), ( "vertical", "vertical" ), ( "onChange", "onChange" ) ]
      , slotRewrites = [ ( "input", "input" ) ]
      , slotKinds = [ ( "unnamed", [ "inputChip" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "linearProgressIndicator"
      , module_ = "M3e.LinearProgressIndicator"
      , enums = [ ( "mode", [ "buffer", "determinate", "indeterminate", "query" ] ), ( "variant", [ "flat", "wavy" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "bufferValue", "bufferValue" ), ( "max", "max" ), ( "mode", "mode" ), ( "value", "value" ), ( "variant", "variant" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "list"
      , module_ = "M3e.List"
      , enums = [ ( "variant", [ "segmented", "standard" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "variant", "variant" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "divider", "expandableListItem", "listAction", "listItem", "listOption" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "listAction"
      , module_ = "M3e.ListAction"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "download", "download" ), ( "href", "href" ), ( "rel", "rel" ), ( "target", "target" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "trailing", "trailing" ) ]
      , slotKinds = [ ( "unnamed", [ "bottomSheetAction", "bottomSheetTrigger", "datepickerToggle", "dialogAction", "dialogTrigger", "drawerToggle", "fabMenuTrigger", "html", "menuTrigger", "navRailToggle", "richTooltipAction", "shared:text", "stepperPrevious", "stepperReset" ] ), ( "leading", [ "avatar", "html", "shared:icon", "shared:text" ] ), ( "overline", [ "html", "shared:text" ] ), ( "supporting-text", [ "html", "shared:text" ] ), ( "trailing", [ "avatar", "checkbox", "html", "radio", "shared:icon", "shared:text", "switch" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = False
      }
    , { component = "listItem"
      , module_ = "M3e.ListItem"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = []
      , slotRewrites = [ ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "trailing", "trailing" ) ]
      , slotKinds = [ ( "unnamed", [ "html", "shared:text" ] ), ( "leading", [ "avatar", "html", "shared:icon", "shared:text" ] ), ( "overline", [ "html", "shared:text" ] ), ( "supporting-text", [ "html", "shared:text" ] ), ( "trailing", [ "avatar", "checkbox", "html", "radio", "shared:icon", "shared:text", "switch" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "listItemButton"
      , module_ = "M3e.ListItemButton"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "download", "download" ), ( "href", "href" ), ( "rel", "rel" ), ( "target", "target" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "trailing", "trailing" ) ]
      , slotKinds = [ ( "unnamed", [ "html", "shared:text" ] ), ( "leading", [ "avatar", "html", "shared:icon", "shared:text" ] ), ( "overline", [ "html", "shared:text" ] ), ( "supporting-text", [ "html", "shared:text" ] ), ( "trailing", [ "avatar", "checkbox", "html", "radio", "shared:icon", "shared:text", "switch" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = False
      }
    , { component = "listOption"
      , module_ = "M3e.ListOption"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "selected", "selected" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "leading", "leading" ), ( "overline", "overline" ), ( "supporting-text", "supportingText" ), ( "trailing", "trailing" ) ]
      , slotKinds = [ ( "unnamed", [ "html", "shared:text" ] ), ( "leading", [ "avatar", "html", "shared:icon", "shared:text" ] ), ( "overline", [ "html", "shared:text" ] ), ( "supporting-text", [ "html", "shared:text" ] ), ( "trailing", [ "avatar", "checkbox", "html", "radio", "shared:icon", "shared:text", "switch" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "loadingIndicator"
      , module_ = "M3e.LoadingIndicator"
      , enums = [ ( "variant", [ "contained", "uncontained" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "variant", "variant" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "menu"
      , module_ = "M3e.Menu"
      , enums = [ ( "positionX", [ "after", "before" ] ), ( "positionY", [ "above", "below" ] ), ( "variant", [ "standard", "vibrant" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "positionX", "positionX" ), ( "positionY", "positionY" ), ( "submenu", "submenu" ), ( "variant", "variant" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "divider", "menuItem", "menuItemCheckbox", "menuItemGroup", "menuItemRadio" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "menuItem"
      , module_ = "M3e.MenuItem"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "download", "download" ), ( "href", "href" ), ( "rel", "rel" ), ( "target", "target" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "bottomSheetAction", "bottomSheetTrigger", "datepickerToggle", "dialogAction", "dialogTrigger", "drawerToggle", "fabMenuTrigger", "menuTrigger", "navRailToggle", "richTooltipAction", "shared:text", "stepperPrevious", "stepperReset" ] ), ( "icon", [ "shared:icon" ] ), ( "trailing-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = False
      }
    , { component = "menuItemCheckbox"
      , module_ = "M3e.MenuItemCheckbox"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ), ( "trailing-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "menuItemGroup"
      , module_ = "M3e.MenuItemGroup"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "menuItem", "menuItemCheckbox", "menuItemRadio" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "menuItemRadio"
      , module_ = "M3e.MenuItemRadio"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ), ( "trailing-icon", "trailingIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ), ( "trailing-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "menuTrigger"
      , module_ = "M3e.MenuTrigger"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "for", "for" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "monthView"
      , module_ = "M3e.MonthView"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "active", "active" ), ( "activeDate", "activeDate" ), ( "date", "date" ), ( "maxDate", "maxDate" ), ( "minDate", "minDate" ), ( "rangeEnd", "rangeEnd" ), ( "rangeStart", "rangeStart" ), ( "today", "today" ), ( "onChange", "onChange" ), ( "onActiveChange", "onActiveChange" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "multiYearView"
      , module_ = "M3e.MultiYearView"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "active", "active" ), ( "activeDate", "activeDate" ), ( "date", "date" ), ( "maxDate", "maxDate" ), ( "minDate", "minDate" ), ( "today", "today" ), ( "onChange", "onChange" ), ( "onActiveChange", "onActiveChange" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "navBar"
      , module_ = "M3e.NavBar"
      , enums = [ ( "mode", [ "auto", "compact", "expanded" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "mode", "mode" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "navItem" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "navItem"
      , module_ = "M3e.NavItem"
      , enums = [ ( "orientation", [ "horizontal", "vertical" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "orientation", "orientation" ), ( "rel", "rel" ), ( "selected", "selected" ), ( "target", "target" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ), ( "selected-icon", "selectedIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ), ( "selected-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = False
      }
    , { component = "navMenu"
      , module_ = "M3e.NavMenu"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "divider", "navMenuItem", "navMenuItemGroup" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "navMenuItem"
      , module_ = "M3e.NavMenuItem"
      , enums = []
      , requiredSlots = [ "label" ]
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "open", "open" ), ( "selected", "selected" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "badge", "badge" ), ( "icon", "icon" ), ( "label", "label" ), ( "selected-icon", "selectedIcon" ), ( "toggle-icon", "toggleIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "navMenuItem" ] ), ( "badge", [ "badge", "shared:text" ] ), ( "icon", [ "shared:icon" ] ), ( "label", [ "shared:link", "shared:text" ] ), ( "selected-icon", [ "shared:icon" ] ), ( "toggle-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "navMenuItemGroup"
      , module_ = "M3e.NavMenuItemGroup"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = []
      , slotRewrites = [ ( "label", "label" ) ]
      , slotKinds = [ ( "unnamed", [ "navMenuItem" ] ), ( "label", [ "heading", "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "navRail"
      , module_ = "M3e.NavRail"
      , enums = [ ( "mode", [ "auto", "compact", "expanded" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "mode", "mode" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "fab", "iconButton", "navItem" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "navRailToggle"
      , module_ = "M3e.NavRailToggle"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "for", "for" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "optgroup"
      , module_ = "M3e.Optgroup"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = []
      , slotRewrites = [ ( "label", "label" ) ]
      , slotKinds = [ ( "unnamed", [ "option" ] ), ( "label", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "option"
      , module_ = "M3e.Option"
      , enums = [ ( "highlightMode", [ "contains", "endsWith", "startsWith" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disableHighlight", "disableHighlight" ), ( "disabled", "disabled" ), ( "highlightMode", "highlightMode" ), ( "selected", "selected" ), ( "term", "term" ), ( "value", "value" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "optionPanel"
      , module_ = "M3e.OptionPanel"
      , enums = [ ( "scrollStrategy", [ "hide", "reposition" ] ), ( "state", [ "content", "loading", "noData" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed", "loading" ]
      , attrRewrites = [ ( "anchorOffset", "anchorOffset" ), ( "fitAnchorWidth", "fitAnchorWidth" ), ( "scrollStrategy", "scrollStrategy" ), ( "state", "state" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ]
      , slotRewrites = [ ( "loading", "loading" ), ( "no-data", "noData" ) ]
      , slotKinds = [ ( "unnamed", [ "divider", "optgroup", "option" ] ), ( "loading", [ "circularProgressIndicator", "loadingIndicator", "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "paginator"
      , module_ = "M3e.Paginator"
      , enums = [ ( "pageSizeVariant", [ "filled", "outlined" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "firstPageLabel", "firstPageLabel" ), ( "hidePageSize", "hidePageSize" ), ( "itemsPerPageLabel", "itemsPerPageLabel" ), ( "lastPageLabel", "lastPageLabel" ), ( "length", "length" ), ( "nextPageLabel", "nextPageLabel" ), ( "pageIndex", "pageIndex" ), ( "pageSize", "pageSize" ), ( "pageSizeVariant", "pageSizeVariant" ), ( "pageSizes", "pageSizes" ), ( "previousPageLabel", "previousPageLabel" ), ( "showFirstLastButtons", "showFirstLastButtons" ), ( "onPage", "onPage" ) ]
      , slotRewrites = [ ( "first-page-icon", "firstPageIcon" ), ( "last-page-icon", "lastPageIcon" ), ( "next-page-icon", "nextPageIcon" ), ( "previous-page-icon", "previousPageIcon" ) ]
      , slotKinds = [ ( "first-page-icon", [ "shared:icon" ] ), ( "last-page-icon", [ "shared:icon" ] ), ( "next-page-icon", [ "shared:icon" ] ), ( "previous-page-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "pseudoCheckbox"
      , module_ = "M3e.PseudoCheckbox"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "indeterminate", "indeterminate" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "pseudoRadio"
      , module_ = "M3e.PseudoRadio"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "radio"
      , module_ = "M3e.Radio"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "name", "name" ), ( "required", "required" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "radioGroup"
      , module_ = "M3e.RadioGroup"
      , enums = []
      , requiredSlots = [ "unnamed" ]
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "ariaInvalid", "ariaInvalid" ), ( "disabled", "disabled" ), ( "name", "name" ), ( "required", "required" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "richTooltip"
      , module_ = "M3e.RichTooltip"
      , enums = [ ( "position", [ "above", "aboveAfter", "aboveBefore", "after", "before", "below", "belowAfter", "belowBefore" ] ), ( "touchGestures", [ "auto", "off", "on" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "hideDelay", "hideDelay" ), ( "position", "position" ), ( "showDelay", "showDelay" ), ( "touchGestures", "touchGestures" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ]
      , slotRewrites = [ ( "actions", "actions" ), ( "subhead", "subhead" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "subhead", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "richTooltipAction"
      , module_ = "M3e.RichTooltipAction"
      , enums = []
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disableRestoreFocus", "disableRestoreFocus" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "ripple"
      , module_ = "M3e.Ripple"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "centered", "centered" ), ( "disabled", "disabled" ), ( "for", "for" ), ( "radius", "radius" ), ( "unbounded", "unbounded" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "scrollContainer"
      , module_ = "M3e.ScrollContainer"
      , enums = [ ( "dividers", [ "above", "aboveBelow", "below", "none" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "dividers", "dividers" ), ( "thin", "thin" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "searchBar"
      , module_ = "M3e.SearchBar"
      , enums = []
      , requiredSlots = [ "input" ]
      , multiSlots = [ "leading", "trailing" ]
      , attrRewrites = [ ( "clearLabel", "clearLabel" ), ( "clearable", "clearable" ), ( "onClear", "onClear" ) ]
      , slotRewrites = [ ( "clear-icon", "clearIcon" ), ( "input", "input" ), ( "leading", "leading" ), ( "trailing", "trailing" ) ]
      , slotKinds = [ ( "clear-icon", [ "shared:icon" ] ), ( "leading", [ "iconButton", "shared:icon" ] ), ( "trailing", [ "iconButton", "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "searchView"
      , module_ = "M3e.SearchView"
      , enums = [ ( "mode", [ "auto", "docked", "fullscreen" ] ) ]
      , requiredSlots = [ "input" ]
      , multiSlots = [ "unnamed", "closed-leading", "closed-trailing", "open-leading", "open-trailing" ]
      , attrRewrites = [ ( "clearLabel", "clearLabel" ), ( "closeLabel", "closeLabel" ), ( "contained", "contained" ), ( "hideSearchIcon", "hideSearchIcon" ), ( "mode", "mode" ), ( "open", "open" ), ( "onQuery", "onQuery" ), ( "onClear", "onClear" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ]
      , slotRewrites = [ ( "clear-icon", "clearIcon" ), ( "close-icon", "closeIcon" ), ( "closed-leading", "closedLeading" ), ( "closed-trailing", "closedTrailing" ), ( "input", "input" ), ( "open-leading", "openLeading" ), ( "open-trailing", "openTrailing" ), ( "search-icon", "searchIcon" ) ]
      , slotKinds = [ ( "clear-icon", [ "shared:icon" ] ), ( "close-icon", [ "shared:icon" ] ), ( "closed-leading", [ "iconButton", "shared:icon" ] ), ( "closed-trailing", [ "iconButton", "shared:icon" ] ), ( "open-leading", [ "iconButton", "shared:icon" ] ), ( "open-trailing", [ "iconButton", "shared:icon" ] ), ( "search-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "segmentedButton"
      , module_ = "M3e.SegmentedButton"
      , enums = []
      , requiredSlots = [ "unnamed" ]
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "multi", "multi" ), ( "name", "name" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "buttonSegment" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "select"
      , module_ = "M3e.Select"
      , enums = []
      , requiredSlots = [ "unnamed" ]
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "multi", "multi" ), ( "name", "name" ), ( "panelClass", "panelClass" ), ( "required", "required" ), ( "onChange", "onChange" ), ( "onToggle", "onToggle" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ]
      , slotRewrites = [ ( "arrow", "arrow" ), ( "value", "value" ) ]
      , slotKinds = [ ( "unnamed", [ "option" ] ), ( "arrow", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "selectionList"
      , module_ = "M3e.SelectionList"
      , enums = [ ( "variant", [ "segmented", "standard" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "hideSelectionIndicator", "hideSelectionIndicator" ), ( "multi", "multi" ), ( "name", "name" ), ( "variant", "variant" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "divider", "expandableListItem", "listOption" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "shape"
      , module_ = "M3e.Shape"
      , enums = [ ( "name", [ "value12SidedCookie", "value4LeafClover", "value4SidedCookie", "value6SidedCookie", "value7SidedCookie", "value8LeafClover", "value9SidedCookie", "arch", "arrow", "boom", "bun", "burst", "circle", "diamond", "fan", "flower", "gem", "ghostIsh", "heart", "hexagon", "oval", "pentagon", "pill", "pixelCircle", "pixelTriangle", "puffy", "puffyDiamond", "semicircle", "slanted", "softBoom", "softBurst", "square", "sunny", "triangle", "verySunny" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "name", "name" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "skeleton"
      , module_ = "M3e.Skeleton"
      , enums = [ ( "animation", [ "none", "pulse", "wave" ] ), ( "shape", [ "auto", "circular", "rounded", "square" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "animation", "animation" ), ( "loaded", "loaded" ), ( "shape", "shape" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "slide"
      , module_ = "M3e.Slide"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "selectedIndex", "selectedIndex" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "slideGroup"
      , module_ = "M3e.SlideGroup"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "nextPageLabel", "nextPageLabel" ), ( "previousPageLabel", "previousPageLabel" ), ( "threshold", "threshold" ), ( "vertical", "vertical" ) ]
      , slotRewrites = [ ( "next-icon", "nextIcon" ), ( "prev-icon", "prevIcon" ) ]
      , slotKinds = [ ( "next-icon", [ "shared:icon" ] ), ( "prev-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "slider"
      , module_ = "M3e.Slider"
      , enums = [ ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "discrete", "discrete" ), ( "labelled", "labelled" ), ( "max", "max" ), ( "min", "min" ), ( "size", "size" ), ( "step", "step" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "sliderThumb"
      , module_ = "M3e.SliderThumb"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "name", "name" ), ( "value", "value" ), ( "onValueChange", "onValueChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "snackbar"
      , module_ = "M3e.Snackbar"
      , enums = []
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "action", "action" ), ( "closeLabel", "closeLabel" ), ( "dismissible", "dismissible" ), ( "duration", "duration" ), ( "onBeforetoggle", "onBeforetoggle" ), ( "onToggle", "onToggle" ) ]
      , slotRewrites = [ ( "close-icon", "closeIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "close-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "splitButton"
      , module_ = "M3e.SplitButton"
      , enums = [ ( "size", [ "extraLarge", "extraSmall", "large", "medium", "small" ] ), ( "variant", [ "elevated", "filled", "outlined", "tonal" ] ) ]
      , requiredSlots = [ "leading-button", "trailing-button" ]
      , multiSlots = []
      , attrRewrites = [ ( "size", "size" ), ( "variant", "variant" ) ]
      , slotRewrites = [ ( "leading-button", "leadingButton" ), ( "trailing-button", "trailingButton" ) ]
      , slotKinds = [ ( "leading-button", [ "button" ] ), ( "trailing-button", [ "iconButton" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "splitPane"
      , module_ = "M3e.SplitPane"
      , enums = [ ( "orientation", [ "auto", "horizontal", "vertical" ] ) ]
      , requiredSlots = [ "end", "start" ]
      , multiSlots = []
      , attrRewrites = [ ( "detents", "detents" ), ( "disabled", "disabled" ), ( "label", "label" ), ( "max", "max" ), ( "min", "min" ), ( "name", "name" ), ( "orientation", "orientation" ), ( "overshootLimit", "overshootLimit" ), ( "step", "step" ), ( "value", "value" ), ( "valueformatter", "valueformatter" ), ( "wrapDetents", "wrapDetents" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ]
      , slotRewrites = [ ( "end", "end" ), ( "start", "start" ) ]
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "stateLayer"
      , module_ = "M3e.StateLayer"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disableHover", "disableHover" ), ( "disabled", "disabled" ), ( "for", "for" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "step"
      , module_ = "M3e.Step"
      , enums = []
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "completed", "completed" ), ( "disabled", "disabled" ), ( "editable", "editable" ), ( "for", "for" ), ( "invalid", "invalid" ), ( "optional", "optional" ), ( "selected", "selected" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "done-icon", "doneIcon" ), ( "edit-icon", "editIcon" ), ( "error", "error" ), ( "error-icon", "errorIcon" ), ( "hint", "hint" ), ( "icon", "icon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "done-icon", [ "shared:icon" ] ), ( "edit-icon", [ "shared:icon" ] ), ( "error", [ "shared:text" ] ), ( "error-icon", [ "shared:icon" ] ), ( "hint", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "stepPanel"
      , module_ = "M3e.StepPanel"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = []
      , slotRewrites = [ ( "actions", "actions" ) ]
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "stepper"
      , module_ = "M3e.Stepper"
      , enums = [ ( "headerPosition", [ "above", "below" ] ), ( "labelPosition", [ "below", "end" ] ), ( "orientation", [ "auto", "horizontal", "vertical" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "panel", "step" ]
      , attrRewrites = [ ( "headerPosition", "headerPosition" ), ( "labelPosition", "labelPosition" ), ( "linear", "linear" ), ( "orientation", "orientation" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ]
      , slotRewrites = [ ( "panel", "panel" ), ( "step", "step" ) ]
      , slotKinds = [ ( "panel", [ "stepPanel" ] ), ( "step", [ "step" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "stepperNext"
      , module_ = "M3e.StepperNext"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "stepperPrevious"
      , module_ = "M3e.StepperPrevious"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "stepperReset"
      , module_ = "M3e.StepperReset"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "suggestionChip"
      , module_ = "M3e.SuggestionChip"
      , enums = [ ( "type_", [ "button", "reset", "submit" ] ), ( "variant", [ "elevated", "outlined" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "disabledInteractive", "disabledInteractive" ), ( "download", "download" ), ( "href", "href" ), ( "name", "name" ), ( "rel", "rel" ), ( "target", "target" ), ( "type_", "type_" ), ( "value", "value" ), ( "variant", "variant" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ), ( "href", "link" ) ]
      , usesAction = True
      }
    , { component = "switch"
      , module_ = "M3e.Switch"
      , enums = [ ( "icons", [ "both", "none", "selected" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "checked", "checked" ), ( "disabled", "disabled" ), ( "icons", "icons" ), ( "name", "name" ), ( "value", "value" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "tab"
      , module_ = "M3e.Tab"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "selected", "selected" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ), ( "onChange", "onChange" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ) ]
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ), ( "icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "tabPanel"
      , module_ = "M3e.TabPanel"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "tabs"
      , module_ = "M3e.Tabs"
      , enums = [ ( "headerPosition", [ "after", "before" ] ), ( "variant", [ "primary", "secondary" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed", "panel" ]
      , attrRewrites = [ ( "disablePagination", "disablePagination" ), ( "headerPosition", "headerPosition" ), ( "nextPageLabel", "nextPageLabel" ), ( "previousPageLabel", "previousPageLabel" ), ( "stretch", "stretch" ), ( "variant", "variant" ), ( "onChange", "onChange" ), ( "onBeforeinput", "onBeforeinput" ), ( "onInput", "onInput" ) ]
      , slotRewrites = [ ( "next-icon", "nextIcon" ), ( "panel", "panel" ), ( "prev-icon", "prevIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "tab" ] ), ( "next-icon", [ "shared:icon" ] ), ( "panel", [ "tabPanel" ] ), ( "prev-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "textHighlight"
      , module_ = "M3e.TextHighlight"
      , enums = [ ( "mode", [ "contains", "endsWith", "startsWith" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "caseSensitive", "caseSensitive" ), ( "disabled", "disabled" ), ( "mode", "mode" ), ( "term", "term" ), ( "onHighlight", "onHighlight" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "textOverflow"
      , module_ = "M3e.TextOverflow"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = []
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "textareaAutosize"
      , module_ = "M3e.TextareaAutosize"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "maxRows", "maxRows" ), ( "minRows", "minRows" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "theme"
      , module_ = "M3e.Theme"
      , enums = [ ( "contrast", [ "high", "medium", "standard" ] ), ( "motion", [ "expressive", "standard" ] ), ( "scheme", [ "auto", "dark", "light" ] ), ( "variant", [ "content", "expressive", "fidelity", "fruitSalad", "monochrome", "neutral", "rainbow", "tonalSpot", "vibrant" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "color", "color" ), ( "contrast", "contrast" ), ( "density", "density" ), ( "motion", "motion" ), ( "scheme", "scheme" ), ( "strongFocus", "strongFocus" ), ( "variant", "variant" ), ( "onChange", "onChange" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "themeIcon"
      , module_ = "M3e.ThemeIcon"
      , enums = [ ( "scheme", [ "auto", "dark", "light" ] ), ( "variant", [ "content", "expressive", "fidelity", "fruitSalad", "monochrome", "neutral", "rainbow", "tonalSpot", "vibrant" ] ) ]
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "color", "color" ), ( "scheme", "scheme" ), ( "variant", "variant" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "toc"
      , module_ = "M3e.Toc"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "for", "for" ), ( "maxDepth", "maxDepth" ) ]
      , slotRewrites = [ ( "overline", "overline" ), ( "title", "title" ) ]
      , slotKinds = [ ( "overline", [ "shared:text" ] ), ( "title", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "tocItem"
      , module_ = "M3e.TocItem"
      , enums = []
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "selected", "selected" ), ( "onClick", "onClick" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "toolbar"
      , module_ = "M3e.Toolbar"
      , enums = [ ( "shape", [ "rounded", "square" ] ), ( "variant", [ "standard", "vibrant" ] ) ]
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "elevated", "elevated" ), ( "shape", "shape" ), ( "variant", "variant" ), ( "vertical", "vertical" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "tooltip"
      , module_ = "M3e.Tooltip"
      , enums = [ ( "position", [ "above", "after", "before", "below" ] ), ( "touchGestures", [ "auto", "off", "on" ] ) ]
      , requiredSlots = [ "unnamed" ]
      , multiSlots = []
      , attrRewrites = [ ( "disabled", "disabled" ), ( "for", "for" ), ( "hideDelay", "hideDelay" ), ( "position", "position" ), ( "showDelay", "showDelay" ), ( "touchGestures", "touchGestures" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "shared:text" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "tree"
      , module_ = "M3e.Tree"
      , enums = []
      , requiredSlots = []
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "cascade", "cascade" ), ( "multi", "multi" ), ( "onChange", "onChange" ) ]
      , slotRewrites = []
      , slotKinds = [ ( "unnamed", [ "treeItem" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    , { component = "treeItem"
      , module_ = "M3e.TreeItem"
      , enums = []
      , requiredSlots = [ "label" ]
      , multiSlots = [ "unnamed" ]
      , attrRewrites = [ ( "disabled", "disabled" ), ( "indeterminate", "indeterminate" ), ( "open", "open" ), ( "selected", "selected" ), ( "onOpening", "onOpening" ), ( "onOpened", "onOpened" ), ( "onClosing", "onClosing" ), ( "onClosed", "onClosed" ), ( "onClick", "onClick" ) ]
      , slotRewrites = [ ( "icon", "icon" ), ( "label", "label" ), ( "open-toggle-icon", "openToggleIcon" ), ( "selected-icon", "selectedIcon" ), ( "toggle-icon", "toggleIcon" ) ]
      , slotKinds = [ ( "unnamed", [ "treeItem" ] ), ( "icon", [ "shared:icon" ] ), ( "label", [ "shared:link", "shared:text" ] ), ( "open-toggle-icon", [ "shared:icon" ] ), ( "selected-icon", [ "shared:icon" ] ), ( "toggle-icon", [ "shared:icon" ] ) ]
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Record, Build ]
      , requiredAttrs = []
      , actionMap = [ ( "onClick", "onClick" ) ]
      , usesAction = False
      }
    , { component = "yearView"
      , module_ = "M3e.YearView"
      , enums = []
      , requiredSlots = []
      , multiSlots = []
      , attrRewrites = [ ( "active", "active" ), ( "activeDate", "activeDate" ), ( "date", "date" ), ( "maxDate", "maxDate" ), ( "minDate", "minDate" ), ( "today", "today" ), ( "onChange", "onChange" ), ( "onActiveChange", "onActiveChange" ) ]
      , slotRewrites = []
      , slotKinds = []
      , slotUpgrades = []
      , groupConstructors = []
      , facets = [ Standard, Build ]
      , requiredAttrs = []
      , actionMap = []
      , usesAction = False
      }
    ]


{-| Kept for the PreferBarrel flatten class; inert on the phantom surface.
-}
reExposedValueTokens : List String
reExposedValueTokens =
    []
