module Sample.AccessibleByConstruction.NamelessCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.AccessibleByConstruction.namelessCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Action
import M3e.Component.IconButton
import TypedHtml.Attributes as TA


shown0_ =
    M3e.Component.IconButton.component
        { content = M3e.icon [ TA.name "help" ] [], action = M3e.Action.none }
        []
        []
