module Compose.Attrs exposing (codeLineFor, kinds, toAttribute, witness)

{- GENERATED by scripts/gen-compose-attrs.mjs — do not edit.

   Derives, from `M3e.Attributes` (setter shapes) and `M3e.Review.Facts`
   (reachable setter names), the attribute kind table the compose editor needs.
   Regenerate with `npm run gen:compose-attrs`; `npm run check:compose-attrs`
   fails the gate on drift.
-}

import Cem.Compose
import Dict exposing (Dict)
import Html
import Html.Attributes
import M3e.Attributes
import M3e.Values


{-| Every reachable, classified attribute name, and its shape. Keyed by the
per-component setter name (the same name `Cem.Compose.attrChips` reports),
because that is what the editor's `Model.attrKinds` is looked up by.
-}
kinds : Dict String Cem.Compose.AttrKind
kinds =
    Dict.fromList
        [ ( "action", Cem.Compose.StringAttr )
        , ( "actionable", Cem.Compose.BoolAttr )
        , ( "active", Cem.Compose.BoolAttr )
        , ( "activeDate", Cem.Compose.StringAttr )
        , ( "alert", Cem.Compose.BoolAttr )
        , ( "anchorOffset", Cem.Compose.FloatAttr )
        , ( "ariaInvalid", Cem.Compose.StringAttr )
        , ( "autoActivate", Cem.Compose.BoolAttr )
        , ( "bounce", Cem.Compose.BoolAttr )
        , ( "bufferValue", Cem.Compose.FloatAttr )
        , ( "cascade", Cem.Compose.BoolAttr )
        , ( "caseSensitive", Cem.Compose.BoolAttr )
        , ( "centered", Cem.Compose.BoolAttr )
        , ( "checked", Cem.Compose.BoolAttr )
        , ( "clearLabel", Cem.Compose.StringAttr )
        , ( "clearable", Cem.Compose.BoolAttr )
        , ( "closeLabel", Cem.Compose.StringAttr )
        , ( "color", Cem.Compose.StringAttr )
        , ( "completed", Cem.Compose.BoolAttr )
        , ( "confirmLabel", Cem.Compose.StringAttr )
        , ( "contained", Cem.Compose.BoolAttr )
        , ( "date", Cem.Compose.StringAttr )
        , ( "dayLabel", Cem.Compose.StringAttr )
        , ( "defaultChecked", Cem.Compose.BoolAttr )
        , ( "defaultSelected", Cem.Compose.BoolAttr )
        , ( "defaultValue", Cem.Compose.StringAttr )
        , ( "density", Cem.Compose.FloatAttr )
        , ( "detent", Cem.Compose.FloatAttr )
        , ( "detents", Cem.Compose.StringAttr )
        , ( "dialLabel", Cem.Compose.StringAttr )
        , ( "disableClose", Cem.Compose.BoolAttr )
        , ( "disableHighlight", Cem.Compose.BoolAttr )
        , ( "disableHover", Cem.Compose.BoolAttr )
        , ( "disableRestoreFocus", Cem.Compose.BoolAttr )
        , ( "disabled", Cem.Compose.BoolAttr )
        , ( "disabledInteractive", Cem.Compose.BoolAttr )
        , ( "discrete", Cem.Compose.BoolAttr )
        , ( "dismissLabel", Cem.Compose.StringAttr )
        , ( "dismissible", Cem.Compose.BoolAttr )
        , ( "download", Cem.Compose.StringAttr )
        , ( "duration", Cem.Compose.FloatAttr )
        , ( "editable", Cem.Compose.BoolAttr )
        , ( "elevated", Cem.Compose.BoolAttr )
        , ( "emphasized", Cem.Compose.BoolAttr )
        , ( "enablePressed", Cem.Compose.BoolAttr )
        , ( "end", Cem.Compose.BoolAttr )
        , ( "endDivider", Cem.Compose.BoolAttr )
        , ( "extended", Cem.Compose.BoolAttr )
        , ( "filled", Cem.Compose.BoolAttr )
        , ( "firstPageLabel", Cem.Compose.StringAttr )
        , ( "fitAnchorWidth", Cem.Compose.BoolAttr )
        , ( "for", Cem.Compose.StringAttr )
        , ( "handle", Cem.Compose.BoolAttr )
        , ( "handleLabel", Cem.Compose.StringAttr )
        , ( "hideDelay", Cem.Compose.FloatAttr )
        , ( "hideFriction", Cem.Compose.FloatAttr )
        , ( "hideLabels", Cem.Compose.BoolAttr )
        , ( "hideLoading", Cem.Compose.BoolAttr )
        , ( "hideModeToggle", Cem.Compose.BoolAttr )
        , ( "hideNoData", Cem.Compose.BoolAttr )
        , ( "hidePageSize", Cem.Compose.BoolAttr )
        , ( "hideRequiredMarker", Cem.Compose.BoolAttr )
        , ( "hideSearchIcon", Cem.Compose.BoolAttr )
        , ( "hideSelectionIndicator", Cem.Compose.BoolAttr )
        , ( "hideToggle", Cem.Compose.BoolAttr )
        , ( "hideable", Cem.Compose.BoolAttr )
        , ( "hour", Cem.Compose.FloatAttr )
        , ( "hourLabel", Cem.Compose.StringAttr )
        , ( "href", Cem.Compose.StringAttr )
        , ( "indeterminate", Cem.Compose.BoolAttr )
        , ( "inline", Cem.Compose.BoolAttr )
        , ( "inputLabel", Cem.Compose.StringAttr )
        , ( "inset", Cem.Compose.BoolAttr )
        , ( "insetEnd", Cem.Compose.BoolAttr )
        , ( "insetStart", Cem.Compose.BoolAttr )
        , ( "invalid", Cem.Compose.BoolAttr )
        , ( "inward", Cem.Compose.BoolAttr )
        , ( "itemLabel", Cem.Compose.StringAttr )
        , ( "itemsPerPageLabel", Cem.Compose.StringAttr )
        , ( "label", Cem.Compose.StringAttr )
        , ( "labelled", Cem.Compose.BoolAttr )
        , ( "lastPageLabel", Cem.Compose.StringAttr )
        , ( "length", Cem.Compose.FloatAttr )
        , ( "level", Cem.Compose.IntAttr )
        , ( "linear", Cem.Compose.BoolAttr )
        , ( "loaded", Cem.Compose.BoolAttr )
        , ( "loading", Cem.Compose.BoolAttr )
        , ( "loadingLabel", Cem.Compose.StringAttr )
        , ( "lowered", Cem.Compose.BoolAttr )
        , ( "max", Cem.Compose.FloatAttr )
        , ( "maxDate", Cem.Compose.StringAttr )
        , ( "maxDepth", Cem.Compose.FloatAttr )
        , ( "maxRows", Cem.Compose.FloatAttr )
        , ( "maxTime", Cem.Compose.StringAttr )
        , ( "min", Cem.Compose.FloatAttr )
        , ( "minDate", Cem.Compose.StringAttr )
        , ( "minRows", Cem.Compose.FloatAttr )
        , ( "minTime", Cem.Compose.StringAttr )
        , ( "minute", Cem.Compose.FloatAttr )
        , ( "minuteLabel", Cem.Compose.StringAttr )
        , ( "modal", Cem.Compose.BoolAttr )
        , ( "modeToggleLabel", Cem.Compose.StringAttr )
        , ( "monthLabel", Cem.Compose.StringAttr )
        , ( "multi", Cem.Compose.BoolAttr )
        , ( "nextMonthLabel", Cem.Compose.StringAttr )
        , ( "nextMultiYearLabel", Cem.Compose.StringAttr )
        , ( "nextPageLabel", Cem.Compose.StringAttr )
        , ( "nextYearLabel", Cem.Compose.StringAttr )
        , ( "noAnimate", Cem.Compose.BoolAttr )
        , ( "noDataLabel", Cem.Compose.StringAttr )
        , ( "noFocusTrap", Cem.Compose.BoolAttr )
        , ( "open", Cem.Compose.BoolAttr )
        , ( "opticalSize", Cem.Compose.FloatAttr )
        , ( "optional", Cem.Compose.BoolAttr )
        , ( "overshootLimit", Cem.Compose.FloatAttr )
        , ( "pageIndex", Cem.Compose.FloatAttr )
        , ( "pageSize", Cem.Compose.StringAttr )
        , ( "pageSizes", Cem.Compose.StringAttr )
        , ( "panelClass", Cem.Compose.StringAttr )
        , ( "periodLabel", Cem.Compose.StringAttr )
        , ( "periodToggleLabel", Cem.Compose.StringAttr )
        , ( "previousMonthLabel", Cem.Compose.StringAttr )
        , ( "previousMultiYearLabel", Cem.Compose.StringAttr )
        , ( "previousPageLabel", Cem.Compose.StringAttr )
        , ( "previousYearLabel", Cem.Compose.StringAttr )
        , ( "radius", Cem.Compose.FloatAttr )
        , ( "range", Cem.Compose.BoolAttr )
        , ( "rangeEnd", Cem.Compose.StringAttr )
        , ( "rangeStart", Cem.Compose.StringAttr )
        , ( "readonly", Cem.Compose.BoolAttr )
        , ( "rel", Cem.Compose.StringAttr )
        , ( "removable", Cem.Compose.BoolAttr )
        , ( "removeLabel", Cem.Compose.StringAttr )
        , ( "required", Cem.Compose.BoolAttr )
        , ( "resultsLabel", Cem.Compose.StringAttr )
        , ( "returnValue", Cem.Compose.StringAttr )
        , ( "second", Cem.Compose.FloatAttr )
        , ( "secondLabel", Cem.Compose.StringAttr )
        , ( "secondary", Cem.Compose.BoolAttr )
        , ( "selected", Cem.Compose.BoolAttr )
        , ( "selectedIndex", Cem.Compose.FloatAttr )
        , ( "showDelay", Cem.Compose.FloatAttr )
        , ( "showFirstLastButtons", Cem.Compose.BoolAttr )
        , ( "showSeconds", Cem.Compose.BoolAttr )
        , ( "start", Cem.Compose.BoolAttr )
        , ( "startAt", Cem.Compose.StringAttr )
        , ( "startDivider", Cem.Compose.BoolAttr )
        , ( "step", Cem.Compose.FloatAttr )
        , ( "stretch", Cem.Compose.BoolAttr )
        , ( "strongFocus", Cem.Compose.BoolAttr )
        , ( "submenu", Cem.Compose.BoolAttr )
        , ( "target", Cem.Compose.StringAttr )
        , ( "term", Cem.Compose.StringAttr )
        , ( "thin", Cem.Compose.BoolAttr )
        , ( "threshold", Cem.Compose.FloatAttr )
        , ( "tocIgnore", Cem.Compose.BoolAttr )
        , ( "today", Cem.Compose.StringAttr )
        , ( "toggle", Cem.Compose.BoolAttr )
        , ( "unbounded", Cem.Compose.BoolAttr )
        , ( "validationmessages", Cem.Compose.StringAttr )
        , ( "value", Cem.Compose.StringAttr )
        , ( "vertical", Cem.Compose.BoolAttr )
        , ( "weight", Cem.Compose.IntAttr )
        , ( "wrap", Cem.Compose.BoolAttr )
        , ( "wrapDetents", Cem.Compose.BoolAttr )
        , ( "yearLabel", Cem.Compose.StringAttr )
        ]


{-| Plain `Html.Attributes.attribute`, stringified per kind. The preview
renders through `Html.node` because which component is on screen is only
known at runtime, so this never touches a typed setter — `witness` below is
what keeps this table honest against `M3e.Attributes` instead.

A half-typed number (`String.toFloat`/`String.toInt` failing) contributes no
attribute at all, rather than a garbage one.

-}
toAttribute : ( String, Cem.Compose.AttrValue ) -> List (Html.Attribute msg)
toAttribute ( name, value ) =
    case value of
        Cem.Compose.AttrBool True ->
            [ Html.Attributes.attribute name "" ]

        Cem.Compose.AttrBool False ->
            []

        Cem.Compose.AttrString s ->
            [ Html.Attributes.attribute name s ]

        Cem.Compose.AttrEnum token ->
            [ Html.Attributes.attribute name (kebab token) ]

        Cem.Compose.AttrFloat raw ->
            String.toFloat raw
                |> Maybe.map (\f -> [ Html.Attributes.attribute name (String.fromFloat f) ])
                |> Maybe.withDefault []

        Cem.Compose.AttrInt raw ->
            String.toInt raw
                |> Maybe.map (\i -> [ Html.Attributes.attribute name (String.fromInt i) ])
                |> Maybe.withDefault []


{-| A camelCase enum token (`"softBoom"`) to the kebab-case string the real
custom element expects on the wire (`"soft-boom"`).
-}
kebab : String -> String
kebab token =
    let
        step char acc =
            if Char.isUpper char then
                acc ++ "-" ++ String.fromChar (Char.toLower char)

            else
                acc ++ String.fromChar char
    in
    String.foldl step "" token


{-| Compile-time only. Every entry references a real `M3e.Attributes` setter
and, for enum rows, a real `M3e.Values` token, so a renamed setter or a
retired token is a compile error HERE rather than a silent no-op at runtime.
Never called.
-}
witness : List ()
witness =
    [ always () (M3e.Attributes.action "")
    , always () (M3e.Attributes.actionable True)
    , always () (M3e.Attributes.active True)
    , always () (M3e.Attributes.activeDate "")
    , always () (M3e.Attributes.alert True)
    , always () (M3e.Attributes.anchorOffset 0)
    , always () (M3e.Attributes.ariaInvalid "")
    , always () (M3e.Attributes.autoActivate True)
    , always () (M3e.Attributes.bounce True)
    , always () (M3e.Attributes.bufferValue 0)
    , always () (M3e.Attributes.cascade True)
    , always () (M3e.Attributes.caseSensitive True)
    , always () (M3e.Attributes.centered True)
    , always () (M3e.Attributes.checked True)
    , always () (M3e.Attributes.clearLabel "")
    , always () (M3e.Attributes.clearable True)
    , always () (M3e.Attributes.closeLabel "")
    , always () (M3e.Attributes.color "")
    , always () (M3e.Attributes.completed True)
    , always () (M3e.Attributes.confirmLabel "")
    , always () (M3e.Attributes.contained True)
    , always () (M3e.Attributes.date "")
    , always () (M3e.Attributes.dayLabel "")
    , always () (M3e.Attributes.defaultChecked True)
    , always () (M3e.Attributes.defaultSelected True)
    , always () (M3e.Attributes.defaultValue "")
    , always () (M3e.Attributes.density 0)
    , always () (M3e.Attributes.detent 0)
    , always () (M3e.Attributes.detents "")
    , always () (M3e.Attributes.dialLabel "")
    , always () (M3e.Attributes.disableClose True)
    , always () (M3e.Attributes.disableHighlight True)
    , always () (M3e.Attributes.disableHover True)
    , always () (M3e.Attributes.disableRestoreFocus True)
    , always () (M3e.Attributes.disabled True)
    , always () (M3e.Attributes.disabledInteractive True)
    , always () (M3e.Attributes.discrete True)
    , always () (M3e.Attributes.dismissLabel "")
    , always () (M3e.Attributes.dismissible True)
    , always () (M3e.Attributes.download "")
    , always () (M3e.Attributes.duration 0)
    , always () (M3e.Attributes.editable True)
    , always () (M3e.Attributes.elevated True)
    , always () (M3e.Attributes.emphasized True)
    , always () (M3e.Attributes.enablePressed True)
    , always () (M3e.Attributes.end True)
    , always () (M3e.Attributes.endDivider True)
    , always () (M3e.Attributes.extended True)
    , always () (M3e.Attributes.filled True)
    , always () (M3e.Attributes.firstPageLabel "")
    , always () (M3e.Attributes.fitAnchorWidth True)
    , always () (M3e.Attributes.for "")
    , always () (M3e.Attributes.handle True)
    , always () (M3e.Attributes.handleLabel "")
    , always () (M3e.Attributes.hideDelay 0)
    , always () (M3e.Attributes.hideFriction 0)
    , always () (M3e.Attributes.hideLabels True)
    , always () (M3e.Attributes.hideLoading True)
    , always () (M3e.Attributes.hideModeToggle True)
    , always () (M3e.Attributes.hideNoData True)
    , always () (M3e.Attributes.hidePageSize True)
    , always () (M3e.Attributes.hideRequiredMarker True)
    , always () (M3e.Attributes.hideSearchIcon True)
    , always () (M3e.Attributes.hideSelectionIndicator True)
    , always () (M3e.Attributes.hideToggle True)
    , always () (M3e.Attributes.hideable True)
    , always () (M3e.Attributes.hour 0)
    , always () (M3e.Attributes.hourLabel "")
    , always () (M3e.Attributes.href "")
    , always () (M3e.Attributes.indeterminate True)
    , always () (M3e.Attributes.inline True)
    , always () (M3e.Attributes.inputLabel "")
    , always () (M3e.Attributes.inset True)
    , always () (M3e.Attributes.insetEnd True)
    , always () (M3e.Attributes.insetStart True)
    , always () (M3e.Attributes.invalid True)
    , always () (M3e.Attributes.inward True)
    , always () (M3e.Attributes.itemLabel "")
    , always () (M3e.Attributes.itemsPerPageLabel "")
    , always () (M3e.Attributes.label "")
    , always () (M3e.Attributes.labelled True)
    , always () (M3e.Attributes.lastPageLabel "")
    , always () (M3e.Attributes.length 0)
    , always () (M3e.Attributes.level 0)
    , always () (M3e.Attributes.linear True)
    , always () (M3e.Attributes.loaded True)
    , always () (M3e.Attributes.loading True)
    , always () (M3e.Attributes.loadingLabel "")
    , always () (M3e.Attributes.lowered True)
    , always () (M3e.Attributes.max 0)
    , always () (M3e.Attributes.maxDate "")
    , always () (M3e.Attributes.maxDepth 0)
    , always () (M3e.Attributes.maxRows 0)
    , always () (M3e.Attributes.maxTime "")
    , always () (M3e.Attributes.min 0)
    , always () (M3e.Attributes.minDate "")
    , always () (M3e.Attributes.minRows 0)
    , always () (M3e.Attributes.minTime "")
    , always () (M3e.Attributes.minute 0)
    , always () (M3e.Attributes.minuteLabel "")
    , always () (M3e.Attributes.modal True)
    , always () (M3e.Attributes.modeToggleLabel "")
    , always () (M3e.Attributes.monthLabel "")
    , always () (M3e.Attributes.multi True)
    , always () (M3e.Attributes.nextMonthLabel "")
    , always () (M3e.Attributes.nextMultiYearLabel "")
    , always () (M3e.Attributes.nextPageLabel "")
    , always () (M3e.Attributes.nextYearLabel "")
    , always () (M3e.Attributes.noAnimate True)
    , always () (M3e.Attributes.noDataLabel "")
    , always () (M3e.Attributes.noFocusTrap True)
    , always () (M3e.Attributes.open True)
    , always () (M3e.Attributes.opticalSize 0)
    , always () (M3e.Attributes.optional True)
    , always () (M3e.Attributes.overshootLimit 0)
    , always () (M3e.Attributes.pageIndex 0)
    , always () (M3e.Attributes.pageSize "")
    , always () (M3e.Attributes.pageSizes "")
    , always () (M3e.Attributes.panelClass "")
    , always () (M3e.Attributes.periodLabel "")
    , always () (M3e.Attributes.periodToggleLabel "")
    , always () (M3e.Attributes.previousMonthLabel "")
    , always () (M3e.Attributes.previousMultiYearLabel "")
    , always () (M3e.Attributes.previousPageLabel "")
    , always () (M3e.Attributes.previousYearLabel "")
    , always () (M3e.Attributes.radius 0)
    , always () (M3e.Attributes.range True)
    , always () (M3e.Attributes.rangeEnd "")
    , always () (M3e.Attributes.rangeStart "")
    , always () (M3e.Attributes.readonly True)
    , always () (M3e.Attributes.rel "")
    , always () (M3e.Attributes.removable True)
    , always () (M3e.Attributes.removeLabel "")
    , always () (M3e.Attributes.required True)
    , always () (M3e.Attributes.resultsLabel "")
    , always () (M3e.Attributes.returnValue "")
    , always () (M3e.Attributes.second 0)
    , always () (M3e.Attributes.secondLabel "")
    , always () (M3e.Attributes.secondary True)
    , always () (M3e.Attributes.selected True)
    , always () (M3e.Attributes.selectedIndex 0)
    , always () (M3e.Attributes.showDelay 0)
    , always () (M3e.Attributes.showFirstLastButtons True)
    , always () (M3e.Attributes.showSeconds True)
    , always () (M3e.Attributes.start True)
    , always () (M3e.Attributes.startAt "")
    , always () (M3e.Attributes.startDivider True)
    , always () (M3e.Attributes.step 0)
    , always () (M3e.Attributes.stretch True)
    , always () (M3e.Attributes.strongFocus True)
    , always () (M3e.Attributes.submenu True)
    , always () (M3e.Attributes.target "")
    , always () (M3e.Attributes.term "")
    , always () (M3e.Attributes.thin True)
    , always () (M3e.Attributes.threshold 0)
    , always () (M3e.Attributes.tocIgnore True)
    , always () (M3e.Attributes.today "")
    , always () (M3e.Attributes.toggle True)
    , always () (M3e.Attributes.unbounded True)
    , always () (M3e.Attributes.validationmessages "")
    , always () (M3e.Attributes.value "")
    , always () (M3e.Attributes.vertical True)
    , always () (M3e.Attributes.weight 0)
    , always () (M3e.Attributes.wrap True)
    , always () (M3e.Attributes.wrapDetents True)
    , always () (M3e.Attributes.yearLabel "")
    , always () (M3e.Attributes.animation M3e.Values.none)
    , always () (M3e.Attributes.animation M3e.Values.pulse)
    , always () (M3e.Attributes.animation M3e.Values.wave)
    , always () (M3e.Attributes.contrast M3e.Values.high)
    , always () (M3e.Attributes.contrast M3e.Values.medium)
    , always () (M3e.Attributes.contrast M3e.Values.standard)
    , always () (M3e.Attributes.current M3e.Values.date)
    , always () (M3e.Attributes.current M3e.Values.location)
    , always () (M3e.Attributes.current M3e.Values.page)
    , always () (M3e.Attributes.current M3e.Values.step)
    , always () (M3e.Attributes.current M3e.Values.time)
    , always () (M3e.Attributes.current M3e.Values.true)
    , always () (M3e.Attributes.disablePagination M3e.Values.auto)
    , always () (M3e.Attributes.disablePagination M3e.Values.false)
    , always () (M3e.Attributes.disablePagination M3e.Values.true)
    , always () (M3e.Attributes.dividers M3e.Values.above)
    , always () (M3e.Attributes.dividers M3e.Values.aboveBelow)
    , always () (M3e.Attributes.dividers M3e.Values.below)
    , always () (M3e.Attributes.dividers M3e.Values.none)
    , always () (M3e.Attributes.endMode M3e.Values.auto)
    , always () (M3e.Attributes.endMode M3e.Values.over)
    , always () (M3e.Attributes.endMode M3e.Values.push)
    , always () (M3e.Attributes.endMode M3e.Values.side)
    , always () (M3e.Attributes.filter M3e.Values.contains)
    , always () (M3e.Attributes.filter M3e.Values.endsWith)
    , always () (M3e.Attributes.filter M3e.Values.none)
    , always () (M3e.Attributes.filter M3e.Values.startsWith)
    , always () (M3e.Attributes.floatLabel M3e.Values.always)
    , always () (M3e.Attributes.floatLabel M3e.Values.auto)
    , always () (M3e.Attributes.format M3e.Values.auto)
    , always () (M3e.Attributes.format M3e.Values.value12)
    , always () (M3e.Attributes.format M3e.Values.value24)
    , always () (M3e.Attributes.grade M3e.Values.high)
    , always () (M3e.Attributes.grade M3e.Values.low)
    , always () (M3e.Attributes.grade M3e.Values.medium)
    , always () (M3e.Attributes.headerPosition M3e.Values.above)
    , always () (M3e.Attributes.headerPosition M3e.Values.after)
    , always () (M3e.Attributes.headerPosition M3e.Values.before)
    , always () (M3e.Attributes.headerPosition M3e.Values.below)
    , always () (M3e.Attributes.hideSubscript M3e.Values.always)
    , always () (M3e.Attributes.hideSubscript M3e.Values.auto)
    , always () (M3e.Attributes.hideSubscript M3e.Values.never)
    , always () (M3e.Attributes.highlightMode M3e.Values.contains)
    , always () (M3e.Attributes.highlightMode M3e.Values.endsWith)
    , always () (M3e.Attributes.highlightMode M3e.Values.startsWith)
    , always () (M3e.Attributes.icons M3e.Values.both)
    , always () (M3e.Attributes.icons M3e.Values.none)
    , always () (M3e.Attributes.icons M3e.Values.selected)
    , always () (M3e.Attributes.labelPosition M3e.Values.below)
    , always () (M3e.Attributes.labelPosition M3e.Values.end)
    , always () (M3e.Attributes.mode M3e.Values.auto)
    , always () (M3e.Attributes.mode M3e.Values.buffer)
    , always () (M3e.Attributes.mode M3e.Values.compact)
    , always () (M3e.Attributes.mode M3e.Values.contains)
    , always () (M3e.Attributes.mode M3e.Values.determinate)
    , always () (M3e.Attributes.mode M3e.Values.dial)
    , always () (M3e.Attributes.mode M3e.Values.docked)
    , always () (M3e.Attributes.mode M3e.Values.endsWith)
    , always () (M3e.Attributes.mode M3e.Values.expanded)
    , always () (M3e.Attributes.mode M3e.Values.fullscreen)
    , always () (M3e.Attributes.mode M3e.Values.indeterminate)
    , always () (M3e.Attributes.mode M3e.Values.input)
    , always () (M3e.Attributes.mode M3e.Values.query)
    , always () (M3e.Attributes.mode M3e.Values.startsWith)
    , always () (M3e.Attributes.motion M3e.Values.expressive)
    , always () (M3e.Attributes.motion M3e.Values.standard)
    , always () (M3e.Attributes.name M3e.Values.arch)
    , always () (M3e.Attributes.name M3e.Values.arrow)
    , always () (M3e.Attributes.name M3e.Values.boom)
    , always () (M3e.Attributes.name M3e.Values.bun)
    , always () (M3e.Attributes.name M3e.Values.burst)
    , always () (M3e.Attributes.name M3e.Values.circle)
    , always () (M3e.Attributes.name M3e.Values.diamond)
    , always () (M3e.Attributes.name M3e.Values.fan)
    , always () (M3e.Attributes.name M3e.Values.flower)
    , always () (M3e.Attributes.name M3e.Values.gem)
    , always () (M3e.Attributes.name M3e.Values.ghostIsh)
    , always () (M3e.Attributes.name M3e.Values.heart)
    , always () (M3e.Attributes.name M3e.Values.hexagon)
    , always () (M3e.Attributes.name M3e.Values.oval)
    , always () (M3e.Attributes.name M3e.Values.pentagon)
    , always () (M3e.Attributes.name M3e.Values.pill)
    , always () (M3e.Attributes.name M3e.Values.pixelCircle)
    , always () (M3e.Attributes.name M3e.Values.pixelTriangle)
    , always () (M3e.Attributes.name M3e.Values.puffy)
    , always () (M3e.Attributes.name M3e.Values.puffyDiamond)
    , always () (M3e.Attributes.name M3e.Values.semicircle)
    , always () (M3e.Attributes.name M3e.Values.slanted)
    , always () (M3e.Attributes.name M3e.Values.softBoom)
    , always () (M3e.Attributes.name M3e.Values.softBurst)
    , always () (M3e.Attributes.name M3e.Values.square)
    , always () (M3e.Attributes.name M3e.Values.sunny)
    , always () (M3e.Attributes.name M3e.Values.triangle)
    , always () (M3e.Attributes.name M3e.Values.value12SidedCookie)
    , always () (M3e.Attributes.name M3e.Values.value4LeafClover)
    , always () (M3e.Attributes.name M3e.Values.value4SidedCookie)
    , always () (M3e.Attributes.name M3e.Values.value6SidedCookie)
    , always () (M3e.Attributes.name M3e.Values.value7SidedCookie)
    , always () (M3e.Attributes.name M3e.Values.value8LeafClover)
    , always () (M3e.Attributes.name M3e.Values.value9SidedCookie)
    , always () (M3e.Attributes.name M3e.Values.verySunny)
    , always () (M3e.Attributes.orientation M3e.Values.auto)
    , always () (M3e.Attributes.orientation M3e.Values.both)
    , always () (M3e.Attributes.orientation M3e.Values.horizontal)
    , always () (M3e.Attributes.orientation M3e.Values.vertical)
    , always () (M3e.Attributes.pageSizeVariant M3e.Values.filled)
    , always () (M3e.Attributes.pageSizeVariant M3e.Values.outlined)
    , always () (M3e.Attributes.period M3e.Values.am)
    , always () (M3e.Attributes.period M3e.Values.pm)
    , always () (M3e.Attributes.position M3e.Values.above)
    , always () (M3e.Attributes.position M3e.Values.aboveAfter)
    , always () (M3e.Attributes.position M3e.Values.aboveBefore)
    , always () (M3e.Attributes.position M3e.Values.after)
    , always () (M3e.Attributes.position M3e.Values.before)
    , always () (M3e.Attributes.position M3e.Values.below)
    , always () (M3e.Attributes.position M3e.Values.belowAfter)
    , always () (M3e.Attributes.position M3e.Values.belowBefore)
    , always () (M3e.Attributes.positionX M3e.Values.after)
    , always () (M3e.Attributes.positionX M3e.Values.before)
    , always () (M3e.Attributes.positionY M3e.Values.above)
    , always () (M3e.Attributes.positionY M3e.Values.below)
    , always () (M3e.Attributes.scheme M3e.Values.auto)
    , always () (M3e.Attributes.scheme M3e.Values.dark)
    , always () (M3e.Attributes.scheme M3e.Values.light)
    , always () (M3e.Attributes.scrollStrategy M3e.Values.hide)
    , always () (M3e.Attributes.scrollStrategy M3e.Values.reposition)
    , always () (M3e.Attributes.shape M3e.Values.auto)
    , always () (M3e.Attributes.shape M3e.Values.circular)
    , always () (M3e.Attributes.shape M3e.Values.rounded)
    , always () (M3e.Attributes.shape M3e.Values.square)
    , always () (M3e.Attributes.size M3e.Values.extraLarge)
    , always () (M3e.Attributes.size M3e.Values.extraSmall)
    , always () (M3e.Attributes.size M3e.Values.large)
    , always () (M3e.Attributes.size M3e.Values.medium)
    , always () (M3e.Attributes.size M3e.Values.small)
    , always () (M3e.Attributes.startMode M3e.Values.auto)
    , always () (M3e.Attributes.startMode M3e.Values.over)
    , always () (M3e.Attributes.startMode M3e.Values.push)
    , always () (M3e.Attributes.startMode M3e.Values.side)
    , always () (M3e.Attributes.startView M3e.Values.month)
    , always () (M3e.Attributes.startView M3e.Values.multiYear)
    , always () (M3e.Attributes.startView M3e.Values.year)
    , always () (M3e.Attributes.state M3e.Values.content)
    , always () (M3e.Attributes.state M3e.Values.loading)
    , always () (M3e.Attributes.state M3e.Values.noData)
    , always () (M3e.Attributes.timeFormat M3e.Values.auto)
    , always () (M3e.Attributes.timeFormat M3e.Values.value12)
    , always () (M3e.Attributes.timeFormat M3e.Values.value24)
    , always () (M3e.Attributes.toggleDirection M3e.Values.horizontal)
    , always () (M3e.Attributes.toggleDirection M3e.Values.vertical)
    , always () (M3e.Attributes.togglePosition M3e.Values.after)
    , always () (M3e.Attributes.togglePosition M3e.Values.before)
    , always () (M3e.Attributes.touchGestures M3e.Values.auto)
    , always () (M3e.Attributes.touchGestures M3e.Values.off)
    , always () (M3e.Attributes.touchGestures M3e.Values.on)
    , always () (M3e.Attributes.type_ M3e.Values.button)
    , always () (M3e.Attributes.type_ M3e.Values.date)
    , always () (M3e.Attributes.type_ M3e.Values.datetime)
    , always () (M3e.Attributes.type_ M3e.Values.reset)
    , always () (M3e.Attributes.type_ M3e.Values.submit)
    , always () (M3e.Attributes.type_ M3e.Values.time)
    , always () (M3e.Attributes.variant M3e.Values.auto)
    , always () (M3e.Attributes.variant M3e.Values.connected)
    , always () (M3e.Attributes.variant M3e.Values.contained)
    , always () (M3e.Attributes.variant M3e.Values.content)
    , always () (M3e.Attributes.variant M3e.Values.display)
    , always () (M3e.Attributes.variant M3e.Values.docked)
    , always () (M3e.Attributes.variant M3e.Values.elevated)
    , always () (M3e.Attributes.variant M3e.Values.expressive)
    , always () (M3e.Attributes.variant M3e.Values.fidelity)
    , always () (M3e.Attributes.variant M3e.Values.filled)
    , always () (M3e.Attributes.variant M3e.Values.flat)
    , always () (M3e.Attributes.variant M3e.Values.fruitSalad)
    , always () (M3e.Attributes.variant M3e.Values.headline)
    , always () (M3e.Attributes.variant M3e.Values.label)
    , always () (M3e.Attributes.variant M3e.Values.modal)
    , always () (M3e.Attributes.variant M3e.Values.monochrome)
    , always () (M3e.Attributes.variant M3e.Values.neutral)
    , always () (M3e.Attributes.variant M3e.Values.outlined)
    , always () (M3e.Attributes.variant M3e.Values.primary)
    , always () (M3e.Attributes.variant M3e.Values.primaryContainer)
    , always () (M3e.Attributes.variant M3e.Values.rainbow)
    , always () (M3e.Attributes.variant M3e.Values.rounded)
    , always () (M3e.Attributes.variant M3e.Values.secondary)
    , always () (M3e.Attributes.variant M3e.Values.secondaryContainer)
    , always () (M3e.Attributes.variant M3e.Values.segmented)
    , always () (M3e.Attributes.variant M3e.Values.sharp)
    , always () (M3e.Attributes.variant M3e.Values.standard)
    , always () (M3e.Attributes.variant M3e.Values.surface)
    , always () (M3e.Attributes.variant M3e.Values.tertiary)
    , always () (M3e.Attributes.variant M3e.Values.tertiaryContainer)
    , always () (M3e.Attributes.variant M3e.Values.text)
    , always () (M3e.Attributes.variant M3e.Values.title)
    , always () (M3e.Attributes.variant M3e.Values.tonal)
    , always () (M3e.Attributes.variant M3e.Values.tonalSpot)
    , always () (M3e.Attributes.variant M3e.Values.uncontained)
    , always () (M3e.Attributes.variant M3e.Values.vibrant)
    , always () (M3e.Attributes.variant M3e.Values.wavy)
    , always () (M3e.Attributes.viewAttr M3e.Values.hour)
    , always () (M3e.Attributes.viewAttr M3e.Values.minute)
    , always () (M3e.Attributes.viewAttr M3e.Values.second)
    , always () (M3e.Attributes.width M3e.Values.default)
    , always () (M3e.Attributes.width M3e.Values.narrow)
    , always () (M3e.Attributes.width M3e.Values.wide)
    ]


{-| The Elm code snippet for one configured attribute (e.g.
`Just "M3e.Attributes.variant M3e.Values.filled"`), or `Nothing` for an
attribute this table does not carry or a number that does not parse. Task 13
assembles these into the generated code preview.
-}
codeLineFor : String -> Cem.Compose.AttrValue -> Maybe String
codeLineFor name value =
    setterFor name
        |> Maybe.andThen (\setter -> literalFor value |> Maybe.map (\lit -> setter ++ " " ++ lit))


setterFor : String -> Maybe String
setterFor name =
    case name of
        "action" ->
            Just "M3e.Attributes.action"

        "actionable" ->
            Just "M3e.Attributes.actionable"

        "active" ->
            Just "M3e.Attributes.active"

        "activeDate" ->
            Just "M3e.Attributes.activeDate"

        "alert" ->
            Just "M3e.Attributes.alert"

        "anchorOffset" ->
            Just "M3e.Attributes.anchorOffset"

        "animation" ->
            Just "M3e.Attributes.animation"

        "ariaInvalid" ->
            Just "M3e.Attributes.ariaInvalid"

        "autoActivate" ->
            Just "M3e.Attributes.autoActivate"

        "bounce" ->
            Just "M3e.Attributes.bounce"

        "bufferValue" ->
            Just "M3e.Attributes.bufferValue"

        "cascade" ->
            Just "M3e.Attributes.cascade"

        "caseSensitive" ->
            Just "M3e.Attributes.caseSensitive"

        "centered" ->
            Just "M3e.Attributes.centered"

        "checked" ->
            Just "M3e.Attributes.checked"

        "clearLabel" ->
            Just "M3e.Attributes.clearLabel"

        "clearable" ->
            Just "M3e.Attributes.clearable"

        "closeLabel" ->
            Just "M3e.Attributes.closeLabel"

        "color" ->
            Just "M3e.Attributes.color"

        "completed" ->
            Just "M3e.Attributes.completed"

        "confirmLabel" ->
            Just "M3e.Attributes.confirmLabel"

        "contained" ->
            Just "M3e.Attributes.contained"

        "contrast" ->
            Just "M3e.Attributes.contrast"

        "current" ->
            Just "M3e.Attributes.current"

        "date" ->
            Just "M3e.Attributes.date"

        "dayLabel" ->
            Just "M3e.Attributes.dayLabel"

        "defaultChecked" ->
            Just "M3e.Attributes.defaultChecked"

        "defaultSelected" ->
            Just "M3e.Attributes.defaultSelected"

        "defaultValue" ->
            Just "M3e.Attributes.defaultValue"

        "density" ->
            Just "M3e.Attributes.density"

        "detent" ->
            Just "M3e.Attributes.detent"

        "detents" ->
            Just "M3e.Attributes.detents"

        "dialLabel" ->
            Just "M3e.Attributes.dialLabel"

        "disableClose" ->
            Just "M3e.Attributes.disableClose"

        "disableHighlight" ->
            Just "M3e.Attributes.disableHighlight"

        "disableHover" ->
            Just "M3e.Attributes.disableHover"

        "disablePagination" ->
            Just "M3e.Attributes.disablePagination"

        "disableRestoreFocus" ->
            Just "M3e.Attributes.disableRestoreFocus"

        "disabled" ->
            Just "M3e.Attributes.disabled"

        "disabledInteractive" ->
            Just "M3e.Attributes.disabledInteractive"

        "discrete" ->
            Just "M3e.Attributes.discrete"

        "dismissLabel" ->
            Just "M3e.Attributes.dismissLabel"

        "dismissible" ->
            Just "M3e.Attributes.dismissible"

        "dividers" ->
            Just "M3e.Attributes.dividers"

        "download" ->
            Just "M3e.Attributes.download"

        "duration" ->
            Just "M3e.Attributes.duration"

        "editable" ->
            Just "M3e.Attributes.editable"

        "elevated" ->
            Just "M3e.Attributes.elevated"

        "emphasized" ->
            Just "M3e.Attributes.emphasized"

        "enablePressed" ->
            Just "M3e.Attributes.enablePressed"

        "end" ->
            Just "M3e.Attributes.end"

        "endDivider" ->
            Just "M3e.Attributes.endDivider"

        "endMode" ->
            Just "M3e.Attributes.endMode"

        "extended" ->
            Just "M3e.Attributes.extended"

        "filled" ->
            Just "M3e.Attributes.filled"

        "filter" ->
            Just "M3e.Attributes.filter"

        "firstPageLabel" ->
            Just "M3e.Attributes.firstPageLabel"

        "fitAnchorWidth" ->
            Just "M3e.Attributes.fitAnchorWidth"

        "floatLabel" ->
            Just "M3e.Attributes.floatLabel"

        "for" ->
            Just "M3e.Attributes.for"

        "format" ->
            Just "M3e.Attributes.format"

        "grade" ->
            Just "M3e.Attributes.grade"

        "handle" ->
            Just "M3e.Attributes.handle"

        "handleLabel" ->
            Just "M3e.Attributes.handleLabel"

        "headerPosition" ->
            Just "M3e.Attributes.headerPosition"

        "hideDelay" ->
            Just "M3e.Attributes.hideDelay"

        "hideFriction" ->
            Just "M3e.Attributes.hideFriction"

        "hideLabels" ->
            Just "M3e.Attributes.hideLabels"

        "hideLoading" ->
            Just "M3e.Attributes.hideLoading"

        "hideModeToggle" ->
            Just "M3e.Attributes.hideModeToggle"

        "hideNoData" ->
            Just "M3e.Attributes.hideNoData"

        "hidePageSize" ->
            Just "M3e.Attributes.hidePageSize"

        "hideRequiredMarker" ->
            Just "M3e.Attributes.hideRequiredMarker"

        "hideSearchIcon" ->
            Just "M3e.Attributes.hideSearchIcon"

        "hideSelectionIndicator" ->
            Just "M3e.Attributes.hideSelectionIndicator"

        "hideSubscript" ->
            Just "M3e.Attributes.hideSubscript"

        "hideToggle" ->
            Just "M3e.Attributes.hideToggle"

        "hideable" ->
            Just "M3e.Attributes.hideable"

        "highlightMode" ->
            Just "M3e.Attributes.highlightMode"

        "hour" ->
            Just "M3e.Attributes.hour"

        "hourLabel" ->
            Just "M3e.Attributes.hourLabel"

        "href" ->
            Just "M3e.Attributes.href"

        "icons" ->
            Just "M3e.Attributes.icons"

        "indeterminate" ->
            Just "M3e.Attributes.indeterminate"

        "inline" ->
            Just "M3e.Attributes.inline"

        "inputLabel" ->
            Just "M3e.Attributes.inputLabel"

        "inset" ->
            Just "M3e.Attributes.inset"

        "insetEnd" ->
            Just "M3e.Attributes.insetEnd"

        "insetStart" ->
            Just "M3e.Attributes.insetStart"

        "invalid" ->
            Just "M3e.Attributes.invalid"

        "inward" ->
            Just "M3e.Attributes.inward"

        "itemLabel" ->
            Just "M3e.Attributes.itemLabel"

        "itemsPerPageLabel" ->
            Just "M3e.Attributes.itemsPerPageLabel"

        "label" ->
            Just "M3e.Attributes.label"

        "labelPosition" ->
            Just "M3e.Attributes.labelPosition"

        "labelled" ->
            Just "M3e.Attributes.labelled"

        "lastPageLabel" ->
            Just "M3e.Attributes.lastPageLabel"

        "length" ->
            Just "M3e.Attributes.length"

        "level" ->
            Just "M3e.Attributes.level"

        "linear" ->
            Just "M3e.Attributes.linear"

        "loaded" ->
            Just "M3e.Attributes.loaded"

        "loading" ->
            Just "M3e.Attributes.loading"

        "loadingLabel" ->
            Just "M3e.Attributes.loadingLabel"

        "lowered" ->
            Just "M3e.Attributes.lowered"

        "max" ->
            Just "M3e.Attributes.max"

        "maxDate" ->
            Just "M3e.Attributes.maxDate"

        "maxDepth" ->
            Just "M3e.Attributes.maxDepth"

        "maxRows" ->
            Just "M3e.Attributes.maxRows"

        "maxTime" ->
            Just "M3e.Attributes.maxTime"

        "min" ->
            Just "M3e.Attributes.min"

        "minDate" ->
            Just "M3e.Attributes.minDate"

        "minRows" ->
            Just "M3e.Attributes.minRows"

        "minTime" ->
            Just "M3e.Attributes.minTime"

        "minute" ->
            Just "M3e.Attributes.minute"

        "minuteLabel" ->
            Just "M3e.Attributes.minuteLabel"

        "modal" ->
            Just "M3e.Attributes.modal"

        "mode" ->
            Just "M3e.Attributes.mode"

        "modeToggleLabel" ->
            Just "M3e.Attributes.modeToggleLabel"

        "monthLabel" ->
            Just "M3e.Attributes.monthLabel"

        "motion" ->
            Just "M3e.Attributes.motion"

        "multi" ->
            Just "M3e.Attributes.multi"

        "name" ->
            Just "M3e.Attributes.name"

        "nextMonthLabel" ->
            Just "M3e.Attributes.nextMonthLabel"

        "nextMultiYearLabel" ->
            Just "M3e.Attributes.nextMultiYearLabel"

        "nextPageLabel" ->
            Just "M3e.Attributes.nextPageLabel"

        "nextYearLabel" ->
            Just "M3e.Attributes.nextYearLabel"

        "noAnimate" ->
            Just "M3e.Attributes.noAnimate"

        "noDataLabel" ->
            Just "M3e.Attributes.noDataLabel"

        "noFocusTrap" ->
            Just "M3e.Attributes.noFocusTrap"

        "onActiveChange" ->
            Just "M3e.Attributes.onActiveChange"

        "onBeforeinput" ->
            Just "M3e.Attributes.onBeforeinput"

        "onBeforetoggle" ->
            Just "M3e.Attributes.onBeforetoggle"

        "onCancel" ->
            Just "M3e.Attributes.onCancel"

        "onChange" ->
            Just "M3e.Attributes.onChange"

        "onClear" ->
            Just "M3e.Attributes.onClear"

        "onClick" ->
            Just "M3e.Attributes.onClick"

        "onClosed" ->
            Just "M3e.Attributes.onClosed"

        "onClosing" ->
            Just "M3e.Attributes.onClosing"

        "onHighlight" ->
            Just "M3e.Attributes.onHighlight"

        "onInput" ->
            Just "M3e.Attributes.onInput"

        "onInvalid" ->
            Just "M3e.Attributes.onInvalid"

        "onOpened" ->
            Just "M3e.Attributes.onOpened"

        "onOpening" ->
            Just "M3e.Attributes.onOpening"

        "onPage" ->
            Just "M3e.Attributes.onPage"

        "onQuery" ->
            Just "M3e.Attributes.onQuery"

        "onRemove" ->
            Just "M3e.Attributes.onRemove"

        "onToggle" ->
            Just "M3e.Attributes.onToggle"

        "onValueChange" ->
            Just "M3e.Attributes.onValueChange"

        "onViewChange" ->
            Just "M3e.Attributes.onViewChange"

        "open" ->
            Just "M3e.Attributes.open"

        "opticalSize" ->
            Just "M3e.Attributes.opticalSize"

        "optional" ->
            Just "M3e.Attributes.optional"

        "orientation" ->
            Just "M3e.Attributes.orientation"

        "overshootLimit" ->
            Just "M3e.Attributes.overshootLimit"

        "pageIndex" ->
            Just "M3e.Attributes.pageIndex"

        "pageSize" ->
            Just "M3e.Attributes.pageSize"

        "pageSizeVariant" ->
            Just "M3e.Attributes.pageSizeVariant"

        "pageSizes" ->
            Just "M3e.Attributes.pageSizes"

        "panelClass" ->
            Just "M3e.Attributes.panelClass"

        "period" ->
            Just "M3e.Attributes.period"

        "periodLabel" ->
            Just "M3e.Attributes.periodLabel"

        "periodToggleLabel" ->
            Just "M3e.Attributes.periodToggleLabel"

        "position" ->
            Just "M3e.Attributes.position"

        "positionX" ->
            Just "M3e.Attributes.positionX"

        "positionY" ->
            Just "M3e.Attributes.positionY"

        "previousMonthLabel" ->
            Just "M3e.Attributes.previousMonthLabel"

        "previousMultiYearLabel" ->
            Just "M3e.Attributes.previousMultiYearLabel"

        "previousPageLabel" ->
            Just "M3e.Attributes.previousPageLabel"

        "previousYearLabel" ->
            Just "M3e.Attributes.previousYearLabel"

        "radius" ->
            Just "M3e.Attributes.radius"

        "range" ->
            Just "M3e.Attributes.range"

        "rangeEnd" ->
            Just "M3e.Attributes.rangeEnd"

        "rangeStart" ->
            Just "M3e.Attributes.rangeStart"

        "readonly" ->
            Just "M3e.Attributes.readonly"

        "rel" ->
            Just "M3e.Attributes.rel"

        "removable" ->
            Just "M3e.Attributes.removable"

        "removeLabel" ->
            Just "M3e.Attributes.removeLabel"

        "required" ->
            Just "M3e.Attributes.required"

        "resultsLabel" ->
            Just "M3e.Attributes.resultsLabel"

        "returnValue" ->
            Just "M3e.Attributes.returnValue"

        "scheme" ->
            Just "M3e.Attributes.scheme"

        "scrollStrategy" ->
            Just "M3e.Attributes.scrollStrategy"

        "second" ->
            Just "M3e.Attributes.second"

        "secondLabel" ->
            Just "M3e.Attributes.secondLabel"

        "secondary" ->
            Just "M3e.Attributes.secondary"

        "selected" ->
            Just "M3e.Attributes.selected"

        "selectedIndex" ->
            Just "M3e.Attributes.selectedIndex"

        "shape" ->
            Just "M3e.Attributes.shape"

        "showDelay" ->
            Just "M3e.Attributes.showDelay"

        "showFirstLastButtons" ->
            Just "M3e.Attributes.showFirstLastButtons"

        "showSeconds" ->
            Just "M3e.Attributes.showSeconds"

        "size" ->
            Just "M3e.Attributes.size"

        "start" ->
            Just "M3e.Attributes.start"

        "startAt" ->
            Just "M3e.Attributes.startAt"

        "startDivider" ->
            Just "M3e.Attributes.startDivider"

        "startMode" ->
            Just "M3e.Attributes.startMode"

        "startView" ->
            Just "M3e.Attributes.startView"

        "state" ->
            Just "M3e.Attributes.state"

        "step" ->
            Just "M3e.Attributes.step"

        "stretch" ->
            Just "M3e.Attributes.stretch"

        "strongFocus" ->
            Just "M3e.Attributes.strongFocus"

        "submenu" ->
            Just "M3e.Attributes.submenu"

        "target" ->
            Just "M3e.Attributes.target"

        "term" ->
            Just "M3e.Attributes.term"

        "thin" ->
            Just "M3e.Attributes.thin"

        "threshold" ->
            Just "M3e.Attributes.threshold"

        "timeFormat" ->
            Just "M3e.Attributes.timeFormat"

        "tocIgnore" ->
            Just "M3e.Attributes.tocIgnore"

        "today" ->
            Just "M3e.Attributes.today"

        "toggle" ->
            Just "M3e.Attributes.toggle"

        "toggleDirection" ->
            Just "M3e.Attributes.toggleDirection"

        "togglePosition" ->
            Just "M3e.Attributes.togglePosition"

        "touchGestures" ->
            Just "M3e.Attributes.touchGestures"

        "type_" ->
            Just "M3e.Attributes.type_"

        "unbounded" ->
            Just "M3e.Attributes.unbounded"

        "validationmessages" ->
            Just "M3e.Attributes.validationmessages"

        "value" ->
            Just "M3e.Attributes.value"

        "variant" ->
            Just "M3e.Attributes.variant"

        "vertical" ->
            Just "M3e.Attributes.vertical"

        "viewAttr" ->
            Just "M3e.Attributes.viewAttr"

        "weight" ->
            Just "M3e.Attributes.weight"

        "width" ->
            Just "M3e.Attributes.width"

        "wrap" ->
            Just "M3e.Attributes.wrap"

        "wrapDetents" ->
            Just "M3e.Attributes.wrapDetents"

        "yearLabel" ->
            Just "M3e.Attributes.yearLabel"

        _ ->
            Nothing


literalFor : Cem.Compose.AttrValue -> Maybe String
literalFor value =
    case value of
        Cem.Compose.AttrBool True ->
            Just "True"

        Cem.Compose.AttrBool False ->
            Just "False"

        Cem.Compose.AttrString s ->
            Just (codeStringLiteral s)

        Cem.Compose.AttrEnum token ->
            Just ("M3e.Values." ++ token)

        Cem.Compose.AttrFloat raw ->
            String.toFloat raw |> Maybe.map String.fromFloat

        Cem.Compose.AttrInt raw ->
            String.toInt raw |> Maybe.map String.fromInt


codeStringLiteral : String -> String
codeStringLiteral s =
    "\"" ++ s ++ "\""
