module M3e.Raw.Heading exposing (heading, emphasized, level, size, variant, tocIgnore)

{-| Bottom layer for `<m3e-heading>`: the plain `elm/html` API — one element constructor plus raw attribute and event setters, faithful DOM emission, no phantom typing. The rawest escape in the gradient.

@docs heading, emphasized, level, size, variant, tocIgnore

-}

import Html
import Html.Attributes


{-| The raw `<m3e-heading>` element — a partial application of `Html.node`.
-}
heading : List (Html.Attribute msg) -> List (Html.Html msg) -> Html.Html msg
heading =
    Html.node "m3e-heading"


{-| Whether the heading uses an emphasized typescale. (default: `false`)
-}
emphasized : Bool -> Html.Attribute msg
emphasized val_ =
    if val_ then
        Html.Attributes.attribute "emphasized" ""

    else
        Html.Attributes.classList []


{-| The accessibility level of the heading.
-}
level : Int -> Html.Attribute msg
level val_ =
    Html.Attributes.attribute "level" (String.fromInt val_)


{-| The size of the heading. (default: `"medium"`)
-}
size : String -> Html.Attribute msg
size =
    Html.Attributes.attribute "size"


{-| The appearance variant of the heading. (default: `"display"`)
-}
variant : String -> Html.Attribute msg
variant =
    Html.Attributes.attribute "variant"


{-| Exclude this heading from the table of contents generated by an `m3e-toc` component. `m3e-toc-ignore` is a valueless presence marker the `m3e-toc` reads from heading elements; it is not an `m3e-heading` CEM attribute, so it is injected here as a heading-scoped synthetic capability.
-}
tocIgnore : Bool -> Html.Attribute msg
tocIgnore val_ =
    if val_ then
        Html.Attributes.attribute "m3e-toc-ignore" ""

    else
        Html.Attributes.classList []
