module Sample.GeneratedAndInspectable.RootCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.GeneratedAndInspectable.rootCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Action
import M3e.Attributes
import M3e.Values as Value


-- your page stays inspectable data all the way up…
saveButton =
    M3e.button { content = M3e.text "Save", action = M3e.Action.none } [ M3e.Attributes.variant Value.filled ] []


-- …and becomes HTML exactly once, at the root:
view model =
    M3e.toNode saveButton
