module Sample.FirstComponent.Source exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.FirstComponent.source`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Attributes
import M3e.Component.Card
import M3e.Values as Value


settingsCard =
    M3e.card [ M3e.Attributes.variant Value.outlined ]
        [ M3e.Component.Card.header
            (M3e.heading [ M3e.Attributes.variant Value.title, M3e.Attributes.level 2 ] [ M3e.text "Account settings" ])
        , M3e.Component.Card.content
            (M3e.button [ M3e.Attributes.variant Value.filled ] [ M3e.text "Save" ])
        ]
