module Sample.Seams.OneWayAccepted exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Seams.oneWayAccepted`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import TypedHtml
import TypedHtml.Attributes as TA


shown0_ =
    TypedHtml.div [] [ M3e.heading { content = M3e.text "hi" } [] [] ]        -- ✓ div takes any children


shown1_ =
    TypedHtml.span [] [ M3e.text "hi" ]                          -- ✓ text is a shared atom


shown2_ =
    TypedHtml.span [] [ M3e.icon [ TA.name "star" ] [] ]         -- ✓ so is icon
