module Sample.Accessibility.FocusCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Accessibility.focusCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Attributes
import M3e.Dialog
import Sample.Support exposing (Msg(..), confirmButtons, model)


-- Elm owns the open STATE; @m3e/web owns the focus trap + Escape + return-focus.
shown0_ =
    M3e.dialog
        [ M3e.Attributes.open model.dialogOpen
        , M3e.Dialog.onClosed CloseDialog
        ]
        [ M3e.Dialog.header (M3e.text "Delete file?")
        , M3e.text "This cannot be undone."
        , M3e.Dialog.actions confirmButtons
        ]
