module Sample.Accessibility.NameCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Accessibility.nameCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Attributes
import M3e.Values as Value
import Sample.Support exposing (on)
import TypedHtml.Aria as Aria
import TypedHtml.Attributes as TA


-- Visible text: the slot content is the name. Nothing extra.
shown0_ =
    M3e.button [ M3e.Attributes.variant Value.filled ] [ M3e.text "Save" ]


-- Icon-only: the name is REQUIRED — supply it explicitly.
shown1_ =
    M3e.iconButton [ Aria.label "Back" ]
        [ M3e.icon [ TA.name "arrow_back" ] [] ]


-- Sneaky case: a Switch/Radio in a list row whose visible label is a SIBLING
-- ListItem text, not its own — it still needs its own name.
shown2_ =
    M3e.switch [ Aria.label "Push notifications", M3e.Attributes.checked on ] []
