module Sample.Seams.OneWayRejected exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.Seams.oneWayRejected`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import TypedHtml


shown0_ =
    TypedHtml.span [] [ M3e.heading { content = M3e.text "hi" } [] [] ]   -- ✗ rejected
