module Sample.TheLayers.DescentCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.TheLayers.descentCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Action
import M3e.Attributes
import M3e.Component.Button
import M3e.Values as Value
import Sample.Support exposing (Msg(..))


-- barrel: one import, the standard form — the default
shown0_ =
    M3e.Component.Button.component { content = M3e.text "Save", action = M3e.Action.onClick Save } [ M3e.Attributes.variant Value.filled ] []


-- component module: same output, component-scoped tighter types — `el` is
-- required-record here because Button can't omit its content/action
shown1_ =
    M3e.Component.Button.component { content = M3e.text "Save", action = M3e.Action.onClick Save } [ M3e.Component.Button.variant Value.filled ] []
