module Sample.CheatSheet.BarrelVsSpecificCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.CheatSheet.barrelVsSpecificCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Action
import M3e.Attributes
import M3e.Component.Button
import M3e.Values as Value
import TypedHtml.Attributes as TA


-- barrel — one import, shared vocabulary (M3e.Attributes.* unions, lint-checked)
shown0_ =
    M3e.button [ M3e.Attributes.variant Value.filled ] [ M3e.Component.Button.icon (M3e.icon [ TA.name "save" ] []), M3e.text "Save" ]


-- component module — component-scoped setters, compile-tight tokens
shown1_ =
    M3e.Component.Button.component { content = M3e.text "Save", action = M3e.Action.none } [ M3e.Component.Button.variant Value.filled ] []
