module Sample.CheatSheet.ShapesCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.CheatSheet.shapesCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Action
import M3e.Component.AppBar
import M3e.Component.Button
import M3e.Values as Value


-- bare form — a component with nothing it can't do without (e.g. AppBar)
shown0_ =
    M3e.Component.AppBar.component [ M3e.Component.AppBar.size Value.medium ] [ M3e.Component.AppBar.title (M3e.text "Inbox") ]


-- required-record form — the compiler demands the parts it can't do without (e.g. Button)
shown1_ =
    M3e.Component.Button.component { content = M3e.text "Save", action = M3e.Action.none } [] []
