module Sample.CheatSheet.ShapesCode exposing (..)

{-| GENERATED by `npm run gen:samples` — do not edit.

This is the Elm shown at `Route.Guide.CheatSheet.shapesCode`, compiled for real.
Change the sample there; this file follows.

-}

import M3e
import M3e.Action
import M3e.Attributes
import M3e.Button
import M3e.Values as Value
import Sample.Support exposing (Msg(..))


-- the standard form — everything optional; the tersest
shown0_ =
    M3e.button [ M3e.Attributes.variant Value.filled ] [ M3e.text "Save" ]


-- required-record form — the compiler demands the parts it can't do without
shown1_ =
    M3e.Button.el { content = M3e.text "Save", action = M3e.Action.onClick Save } [] []


-- builder pipe — a one-only setter is unwritable twice; order-free
shown2_ =
    M3e.Button.build { content = M3e.text "Save", action = M3e.Action.onClick Save }
        |> M3e.Button.toElement
