module Main exposing (main)

-- GENERATED by `npm run gen:samples` from `Route.GettingStarted.Installation.mainModule` — do not edit.

import Browser
import Html
import M3e
import M3e.Button as Button
import M3e.Theme as Theme
import M3e.Values as Value


main : Program () () ()
main =
    Browser.sandbox { init = (), update = \_ model -> model, view = view }


view : () -> Html.Html ()
view _ =
    M3e.toHtml
        (Theme.view
            [ Theme.color "#6750A4"
            , Theme.scheme Value.auto
            ]
            [ Button.view
                [ Button.variant Value.filled ]
                [ M3e.text "It works" ]
            ]
        )
