module Main exposing (main)

-- GENERATED by `npm run gen:samples` from `Route.GettingStarted.Installation.mainModule` — do not edit.

import Browser
import Html
import M3e
import M3e.Action
import M3e.Component.Button as Button
import M3e.Component.Theme as Theme
import M3e.Values as Value
import M3e.Component.Heading


main : Program () () ()
main =
    Browser.sandbox { init = (), update = \_ model -> model, view = view }


view : () -> Html.Html ()
view _ =
    let
        app =
            Theme.component
                [ Theme.color "#6750A4"
                , Theme.scheme Value.auto
                ]
                [ Button.component
                    { content = M3e.text "It works", action = M3e.Action.none }
                    [ Button.variant Value.filled ]
                    []
                ]
    in
    M3e.toHtml app
