module Guide.Samples exposing
    ( guideEmailField
    , guideHelpButton
    , guideSavedButton
    , seamsHtmlInSlot
    , seamsLinkNav
    , seamsModelViewer
    , seamsTwoColumn
    )

{-| GENERATED by `npm run gen:samples` — do not edit.

Guide pages that render a live helper AND show its code get the shown code
from here: each string below is the _source text of that helper_, lifted out
of the route module it lives in. A page and the thing it is teaching cannot
drift apart, because there is only one of them.

Marked at the source with `-- @sample-source <name>`.

@docs guideEmailField
@docs guideHelpButton
@docs guideSavedButton
@docs seamsHtmlInSlot
@docs seamsLinkNav
@docs seamsModelViewer
@docs seamsTwoColumn

-}


{-| `emailField`, from `docs/app/Route/Guide/CompositionTextField.elm`.
-}
guideEmailField : String
guideEmailField =
    """emailField =
    M3e.formField [ M3e.FormField.variant Value.outlined ]
        [ M3e.FormField.label
            (TypedHtml.label [ TypedHtml.Attributes.for "email-field" ] [ M3e.text "Email address" ])
        , M3e.FormField.hint (M3e.text "We'll never share it.")
        , TypedHtml.input
            [ TypedHtml.Attributes.id "email-field"
            , TypedHtml.Attributes.type_ "email"
            , TypedHtml.Attributes.placeholder "you@example.com"
            , TypedHtml.Attributes.name "email"
            ]
            []
        ]"""


{-| `helpButton`, from `docs/app/Route/Guide/AccessibleByConstruction.elm`.
-}
guideHelpButton : String
guideHelpButton =
    """M3e.iconButton [ Aria.label "Help" ]
    [ M3e.icon [ TA.name "help" ] [] ]"""


{-| `savedButton`, from `docs/app/Route/Guide/InvalidStates.elm`.
-}
guideSavedButton : String
guideSavedButton =
    """M3e.button [ M3e.Attributes.variant Value.filled ]
    [ M3e.Button.icon (M3e.icon [ TA.name "save" ] [])
    , M3e.text "Save"
    ]"""


{-| `htmlInSlot`, from `docs/app/Route/Guide/Seams.elm`.
-}
seamsHtmlInSlot : String
seamsHtmlInSlot =
    """htmlInSlot =
    -- AppBar.TrailingSlot admits { button, iconButton, searchBar, sharedFlow, sharedPhrasing }.
    -- `TypedHtml.div` produces `sharedFlow`, so the wrapper goes in as itself — and the
    -- iconButton and badge INSIDE it are still checked against the div's content model.
    M3e.appBar [ TypedHtml.Attributes.class "px-2" ]
        [ M3e.AppBar.title (M3e.heading [] [ M3e.text "Inbox" ])
        , M3e.AppBar.trailing
            (TypedHtml.div [ TypedHtml.Attributes.class "inline-flex items-center gap-1" ]
                [ M3e.iconButton [ TypedHtml.Aria.label "Search" ] [ M3e.icon [ TypedHtml.Attributes.name "search" ] [] ]
                , M3e.badge [] [ M3e.text "3" ]
                ]
            )
        ]"""


{-| `linkNav`, from `docs/app/Route/Guide/Seams.elm`.
-}
seamsLinkNav : String
seamsLinkNav =
    """linkNav =
    -- the label slot admits { text : M3e.Kind.Brand, link : M3e.Kind.Brand }, so a
    -- typed `TypedHtml.a` fills it directly — a nav item that IS an anchor. The
    -- required-record form (`M3e.NavMenuItem.el`) enforces the required `label`.
    M3e.navMenu []
        [ M3e.NavMenuItem.el { label = TypedHtml.a [ TypedHtml.Attributes.href "/guide/seams" ] [ M3e.text "Seams" ] } [] []
        , M3e.NavMenuItem.el { label = TypedHtml.a [ TypedHtml.Attributes.href "/guide/the-layers" ] [ M3e.text "The surfaces" ] } [] []
        ]"""


{-| `modelViewer`, from `docs/app/Route/Guide/Seams.elm`.
-}
seamsModelViewer : String
seamsModelViewer =
    """modelViewer =
    -- a real seam: a custom element the types can't express, contained once.
    M3e.Unsafe.customElement "model-viewer"
        [ TypedHtml.Attributes.src "/models/chair.glb"
        , M3e.Unsafe.Attributes.customAttribute "camera-controls" ""
        , M3e.Unsafe.Attributes.customAttribute "auto-rotate" ""
        , TypedHtml.Attributes.class "block h-48 w-full rounded-lg bg-surface-container"
        ]
        []"""


{-| `twoColumn`, from `docs/app/Route/Guide/Seams.elm`.
-}
seamsTwoColumn : String
seamsTwoColumn =
    """twoColumn =
    -- NOT a seam: standard HTML is already typed, so layout is a plain div.
    TypedHtml.div [ TypedHtml.Attributes.class "grid grid-cols-1 gap-4 md:grid-cols-2" ]
        [ emailField, saveButton ]"""
